### ISSUE TITLE
Add `cats.data.Validation`

### ISSUE THREAD

**Issue by adelbertc** [non/cats#104]
Do we want to do this as a separate data type, or should we explore the tagged type approach?

Also related to #31

**Comment by adelbertc** [comment]
@stew has an example of the tagged type approach [here](https://github.com/stew/funlib/blob/ditch-scalaz/core/src/main/scala/Sum.scala)

**Comment by rossabaker** [comment]
There was also discussion of [Scalactic's Or And Every](http://www.scalactic.org/) (scroll down; no anchor) in gitter.

**Comment by mpilquist** [comment]
I'm not convinced that type tagging in scala works all that well -- or at least if it does, I'm not sure we've found the right solution yet. See the bugs fixed and new bugs introduced by scalaz 7.1's tagging as compared to 7.0.

**Comment by stew** [comment]
I'm going to throw together a Validation class

**Comment by ceedubs** [comment]
Fixed by #239
