### ISSUE TITLE
Add sbt task to validate a pull request?

### ISSUE THREAD

**Issue by fthomas** [non/cats#112]
The contributor guide mentions that one should run the `compile`, `unidoc`, and `scalastyle` tasks before submitting a PR. It would be nice if those could be subsumed under a new `validateMyPR` task so that you have to remeber only one task to run before submitting a PR.

**Comment by ceedubs** [comment]
:+1:!

And don't forget about the `test` subtask!

**Comment by ceedubs** [comment]
Actually I'll give this a quick try. I'm bad with SBT but this seems like it should be simple enough.

**Comment by ceedubs** [comment]
Okay I admit defeat. Hopefully someone smarter than I can figure out how to aggregate tasks with SBT :(

**Comment by ceedubs** [comment]
Also this task should perform `test:scalastyle`, and then we should have the travis script run this task. I missed `test:scalastyle` in #84. I'll submit a separate PR for that as an interim solution until this issue is completed.

**Comment by fthomas** [comment]
This seems to do the trick:
`addCommandAlias("validatePR", ";compile;test;scalastyle;test:scalastyle;unidoc")`

**Comment by ceedubs** [comment]
@fthomas ah thanks! I'm turning this into a PR now.
