### ISSUE TITLE
Organization of AnyRef instances

### ISSUE THREAD

**Issue by ceedubs** [non/cats#118]
Currently the `BigInt` and `BigDecimal` instances reside in `anyref.scala` and are mixed into `AnyRefInstances`. Since we have other `AnyRef` instances (String, Option, etc), this seems kind of odd to me. Should they just get their own files and instance traits like other std lib types?

**Comment by non** [comment]
Yes, I think we should just have `cats.std.bigInt` and `cats.std.bigDecimal` (or whatever case we decide upon).

**Comment by adelbertc** [comment]
i got this

**Comment by ceedubs** [comment]
Fixed by #138
