### ISSUE TITLE
Try[A] => Throwable Or A

### ISSUE THREAD

**Issue by ceedubs** [non/cats#119]
We should provide a helper method to convert `Try[A]` into `Throwable Or A`.

It probably makes sense to put this on the `Or` companion object, because the `std` module does not depend on the `data` module. However, this does raise the question of whether we are going to have syntax for things like `Try.toOr`, `Either.toOr`. `List.toNonEmptyList`, etc. If so, where would it go?

Also this could be implemented as an isomophism with something like `Try <~> Or[Throwable, ?]`, but as far as I know we don't have this sort of isomorphism defined in Cats. Do we want it?

**Comment by bobbyrauchenberg** [comment]
I'd love to pick this up, I don't completely understand the last paragraph (aplogies), but i'm happy to go away and do some reading, if you can maybe tolerate a few dumb questions down the line?

**Comment by rossabaker** [comment]
Since it looks like we settled on `fromTry`, I think there should also be a `fromEither`.

**Comment by ceedubs** [comment]
@rossabaker good idea. I just created #163.
