### ISSUE TITLE
write a description of typeclasses

### ISSUE THREAD

**Issue by stew** [non/cats#127]
we need a docs/src/main/tut/typeclasses.md or a docs/src/site/typeclasses.md that talks about what typeclasses are.

Assigning to @ceedubs  since you've presented this material multiple times.

test by running docs/makeSite and then running `jekyll serve` in the docs/target/site dir

**Comment by tpolecat** [comment]
I have an old [blog post](http://tpolecat.github.io/2013/10/12/typeclass.html) that's in [tut format](https://raw.githubusercontent.com/tpolecat/tut/master/example/src/main/tut/Typeclass.md) already, if that's helpful. Probably needs some `:silent` markers.

**Comment by stew** [comment]
moving this out of ready until the sbt-site PR is merged

**Comment by ceedubs** [comment]
Wow @tpolecat that post is really good. Other than perhaps linking to `algebra`'s `Monoid` at the end, I'm really not sure what I could do better. Do you want your post to be lifted into cats docs, or would you prefer we create a completely separate doc?

**Comment by tpolecat** [comment]
@ceedubs feel free to steal as much or as little of that as you want. Just offering it as a resource. I think it's ok as a worked example, but it could use some words about typeclasses as the basic design pattern for cats and the benefits of ad-hoc polymorphism (in this case, you can't do monoid zero with subtyping, and append would require an F-bounded type). I guess it just needs to be oriented with respect to cats.
