### ISSUE TITLE
create a monad.md explaining what a monad is

### ISSUE THREAD

**Issue by stew** [non/cats#128]
no burritos allowed.

create docs/src/main/tut/monad.md similar to functor.md and apply.md

test by running docs/makeSite and then running jekyll serve in the docs/target/site dir

**Comment by woparry** [comment]
I will do this.

**Comment by woparry** [comment]
#332

**Comment by InTheNow** [comment]
Shouldn't this have been closed with #332?

**Comment by ceedubs** [comment]
@InTheNow yep! Good catch.
