### ISSUE TITLE
add a benchmark module and start comparing our impl with std

### ISSUE THREAD

**Issue by julien-truffaut** [non/cats#134]
If we want to be serious about performance, I believe that we need reliable and reproductible benchmarks. For example, we could compare performance of `cats.data.Or` with `scala.Either`.

**Comment by julien-truffaut** [comment]
If we want to use [jmh](http://openjdk.java.net/projects/code-tools/jmh/), I can set it up. What are your experience with other benchmark frameworks?

**Comment by ceedubs** [comment]
:+1:

I've never actually used jmh and have very little benchmarking experience, but I remember reading [this](https://groups.google.com/forum/#!msg/mechanical-sympathy/m4opvy4xq3U/7lY8x8SvHgwJ) once and being impressed. As it turns out, proper benchmarking on the JVM is not a simple thing.

**Comment by ijuma** [comment]
jmh is definitely the way forward. I created a PR for spire a few months ago:

https://github.com/non/spire/pull/307

**Comment by julien-truffaut** [comment]
fix #190
