### ISSUE TITLE
Laws for MonadFilter and MonadCombine

### ISSUE THREAD

**Issue by non** [non/cats#135]
Both of these have laws that we aren't currently testing.

The important one is `MonadFilter` since it introduces a new method (`empty`) which isn't participating in any of its "inherited" laws. But there are also laws for how `empty` and `combine` interact with `flatMap` which we should be testing for `MonadCombine` as well.

See #125 for more discussion.

**Comment by xuwei-k** [comment]
`cats.MonadFilter` ≒ `MonadZero` ?

https://wiki.haskell.org/MonadPlus_reform_proposal

**Comment by fthomas** [comment]
I'll work on this one.

**Comment by mpilquist** [comment]
@fthomas It might be good to do #212 first because MonadCombineLaws depend on AlternativeLaws.

**Comment by mpilquist** [comment]
Oh, and in order to write AlternativeLaws, you'll need the soon to be merged MonoidKLaws

**Comment by fthomas** [comment]
Thanks for the hint. I'll postpone the `MonadCombineLaws` then and just submit a PR for the `MonadFilterLaws`.

**Comment by fthomas** [comment]
This should be fixed by #198, #215, and #223.
