### ISSUE TITLE
Add compose instances for Invariant and Contravariant

### ISSUE THREAD

**Issue by mpilquist** [non/cats#148]
We should add support for composing:
 - `Invariant` and `Invariant`, yielding `Invariant`
 - `Invariant` and `Functor`, yielding `Invariant`
 - `Invariant` and `Contravariant`, yielding `Invariant`
 - `Contravariant ` and `Contravariant `, yielding `Functor`
 - `Contravariant ` and `Functor `, yielding `Contravariant`
 - `Functor ` and `Contravariant `, yielding `Contravariant`

See equivalents in Structures for examples:
 - https://github.com/mpilquist/Structures/blob/24d40bd39db7f1cf60bd63154b44540deb7f667e/core/src/main/scala/structures/Exponential.scala#L18-L34
 - https://github.com/mpilquist/Structures/blob/24d40bd39db7f1cf60bd63154b44540deb7f667e/core/src/main/scala/structures/Contravariant.scala#L12-L25
 - https://github.com/mpilquist/Structures/blob/24d40bd39db7f1cf60bd63154b44540deb7f667e/core/src/main/scala/structures/Functor.scala#L43-L61

**Comment by coltfred** [comment]
I'll start on this.

**Comment by ceedubs** [comment]
Fixed by #165
