### ISSUE TITLE
Add better documentation for Invariant

### ISSUE THREAD

**Issue by non** [non/cats#164]
We just had a conversation about what `Invariant` / `imap` was for on Gitter.

@mpilquist provided a link to a blog post he wrote about it: http://mpilquist.github.io/blog/2013/06/01/scodec-part-2/

@coltfred suggests that we could either link to that, or summarize it in a block comment. Obviously we don't have to get this perfect immediately, we can just make incremental progress.

**Comment by mpilquist** [comment]
Lots more detail here: https://github.com/mpilquist/variance-explorations

Note - slides were for a non-Scala meetup, so they go in to a lot of detail. There are lots of slides to make up for that though. :)

Also, see Ed Kmett's blog, which is where I learned this stuff originally: http://comonad.com/reader/2008/rotten-bananas/

**Comment by ceedubs** [comment]
See also #423 which has an example that could be turned into documentation.
