### ISSUE TITLE
Mobile friendly docs layout

### ISSUE THREAD

**Issue by refried** [non/cats#179]
See: http://imgur.com/ReppMGC

Someone think of the @ceedubs! :-)

**Comment by non** [comment]
Haha, agreed.

**Comment by ceedubs** [comment]
The 8% battery life in this image causes me an unreasonable amount of stress.

**Comment by refried** [comment]
@ceedubs It was causing me stress too. :smile:  It was down to 1% before I made it to a charger.

**Comment by refried** [comment]
Should this issue have a `ready` tag?  I would try to fix it myself, but not CSS-savvy enough.

**Comment by stew** [comment]
this was fixed by #248
