### ISSUE TITLE
Scala.JS support

### ISSUE THREAD

**Issue by betehess** [non/cats#18]
I would like to check how much interest there is in taking Scala.JS seriously in cats.

That might not be an easy decision to make but it could actually be :-)

**Comment by non** [comment]
So, I am definitely interested in exploring it. There's a lot of excitement behind Scala.js right.

The fact that we are trying to have a modular design would hopefully make the library easier to use (in terms of JS size). I'm not sure what we'd need to do to the project to allow it to build in both places.

Note that we would need our [algebra](https://github.com/non/algebra) as well. I don't think this is a huge deal but it would be more work for sure.

**Comment by betehess** [comment]
Sounds good. I can do a first pass at algebra then.

**Comment by weihsiu** [comment]
+100!  we are currently using scalajs with japgolly's scalaz build.  it would be very interesting to have cats support scalajs as well.

**Comment by InTheNow** [comment]
If people want, I would be more than happy to have a crack at this one. Looking at Algebra first, the first thing I see is that is uses Discipline and scalatest. 

In order to cross-compile scala, we also need to cross compile tests and hence need a test framework that supports this. There are a few, but not scalatest and specs2. 

So the first step, that cuts across the whole project, is to pick a suitable test framework. I can offer my own personal opinions/advice on this, but cannot make/push anything on this. 

@larsrh  We discussed doing this with zCheck, migrating that to discipline as and when you had time. Any thoughts on this?

**Comment by japgolly** [comment]
+1. Scala.JS support would be widely appreciated. The initial setup is relatively quick and the ongoing maintenance is trivial, plus there are plenty of enthusiasts like myself who would be happy to help if there are issues.

Re property testing, if you're open to something different I humbly suggest having a look at [Nyaya](https://github.com/japgolly/nyaya). It's written by me, and is Scala.JS compatible.

Finally, I read somewhere that ScalaTest might be publishing a Scala.JS build but like @InTheNow says, there are a few new libs already.

**Comment by ngbinh** [comment]
:100: there is nothing more satisfying than working on a type check web client.

**Comment by stew** [comment]
do we have concrete items that people can work on for this? I see testing in the older comments, but perhaps that has changed since these comments were made, as clearly there is a lot of momentum behind scalajs

**Comment by InTheNow** [comment]
@stew - It's all well under way. eg https://github.com/non/cats/tree/topic/sjs . I'm a bit busy this minute, but later will write up what I've done, etc.

**Comment by InTheNow** [comment]
The general process for adding Scala.js(sjs) support to a JVM project is to modify the build to :
- cross-compile the code, including the test code, to jvm/sjs. This is usually
achieved with the sjs CrossProject class
 (Alternatively, there is the shapless approach of having a git branch per platform) 
- include sjs versions of libs for the sjs build, including any test frameworks, coverage tools, etc. There is thus an implicit requirement that all dependant libs have been previously released for sjs


The initial port has been done, and the code compiles. However, as not all the dependent libraries have been ported to sjs, the code cannot be linked to JS and hence cannot be tested.

The test libs in question are:
 - scalatest: release snapshot done, so this can be used in cats and the dependant libs
 - scoverage: Currently only in cats (almost). There is an issue here that the plugin
 does not support "shared" directories and so cannot be used in CrossProjects,
 not even for jvm only coverage. Hence any project must either 
a) Use scoverage and not use CrossProject, but can use the one-branch-per-platform
 approach. Or 
b) use CrossProject, but do not use scoverage for now (a fix will come...sometime https://github.com/scoverage/sbt-scoverage/issues/111).     

Other libs:
- simulacrum - needs scalatest.js. @inthenow can look,  @mpilquist Is this OK with CrossProject? 
- machinist - Done needs releasing, issue with Bintray -  @inthenow can look
- discipline - done locally by @inthenow, can also add scalatest.js. @larsrh  Is this OK with CrossProject?
- kind-projector, algebra:   @inthenow can look,  @non Is this OK with CrossProject? 

For cats itself, having code coverage looks essential for now, so I would suggest the git branch approach for now (and on behalf of @milessabin, later too).

Feedback/suggestions welcome :)

**Comment by mpilquist** [comment]
@InTheNow I'm all for doing whatever needs to be done to make simulacrum work with SJS. I didn't think we'd need to build SJS artifacts since simulacrum shouldn't be on the runtime classpath. That was just an assumption though.

**Comment by InTheNow** [comment]
@mpilquist Excellent- I'll build all the modules locally first so I can be sure they all work as they should, are actually required, etc

**Comment by InTheNow** [comment]
Forgot to add link to https://github.com/scalatest/scalatest/issues/631, only known blocker.
