### ISSUE TITLE
Cokleisli compose is left-to-right composition

### ISSUE THREAD

**Issue by fthomas** [non/cats#180]
Currently `Cokleisli#compose` is left-to-right composition `(F[A] => B) => (F[B] => C) => (F[A] => C)` while `andThen` is right-to-left composition `(F[B] => C) => (F[A] => B) => (F[A] => C)`. This is the opposite of how `compose` and `andThen` are defined for `Kleisli` and `Function1`. The composition functions should be consistent across `Kleisli`, `Cokleisli`, `Function1`, etc.

**Comment by mandubian** [comment]
I take it

**Comment by fthomas** [comment]
This will probably interfere wtih #141.

**Comment by mandubian** [comment]
So let's wait until it's merged ;)
