### ISSUE TITLE
Move 'free' and 'arrow' packages out of 'core'

### ISSUE THREAD

**Issue by non** [non/cats#183]
We've been planning to do this for awhile, to try to keep 'core' lightweight.

I just created this issue to have a place to discuss the move, and also to help remind folks that it is going to happen.

**Comment by mandubian** [comment]
Maybe I could do that first and then move my Free stuff to this new project to make everything clean

**Comment by julien-truffaut** [comment]
I can see the point for `Free` to have its own module as there are no typeclasses in `cats.free` but I don't see why `arrow` should go out of `core`.

**Comment by mandubian** [comment]
I agree arrow seems ok in core!

**Comment by refried** [comment]
Should we put a Ready tag on this?

**Comment by mandubian** [comment]
where do we move it? (I've got another PR I coudn't finish yet containing Free doc & FreeApp)

**Comment by refried** [comment]
`free.dependsOn(core)` and `free/` and `cats.free` ?

**Comment by refried** [comment]
Why not move all of `cats.free` into `data`?  What is `data`?  Why not leave `cats.free` in `core`?  (Sorry.)

**Comment by mandubian** [comment]
there have been some discussions about `data` status but I'm not sure where it ended because I couldn't follow cats recently

**Comment by ceedubs** [comment]
I vote for what @refried said in https://github.com/non/cats/issues/183#issuecomment-78096432. There may be other modules that need to depend on free but don't want to depend on `data`. Moreover, I'd just like to see `State` get out the door and we can always move things around later if we start to see signs that our choice of module breakdown is wrong :)

**Comment by mandubian** [comment]
Making `free` its own project would be interesting as we could also test other Free approaches in it.
`Free` is a subject in itself...

**Comment by fthomas** [comment]
Closing because `free` has been moved into a separate module in #205.
