### ISSUE TITLE
its hard to use Id

### ISSUE THREAD

**Issue by stew** [non/cats#185]
Because of the current structure with the Id type alias defined in pacakge.scala and the typeclass instances in the Id object, you can't use the Id object if you `import cats._`, Here's a repl session:

```
scala> cats.Id.id.map(1)(_ + 1)
res0: cats.Id[Int] = 2

scala> import cats._
import cats._

scala> cats.Id.id.map(1)(_ + 1)
<console>:11: error: value id is not a member of object cats.Id
              cats.Id.id.map(1)(_ + 1)
                      ^
```

I think we might need to move the type alias to the Id object

**Comment by ceedubs** [comment]
Could someone please explain to me what goes wrong here? I see that it happens even if you just import `cats.Id` as opposed to `cats._`. I don't see why that should cause a problem. Is this just a wart in Scala, or is there a logical explanation of why this is problematic?

**Comment by ceedubs** [comment]
I separately ran into a similar issue with `StateT`/`State`. It looks like [SI-7139](https://issues.scala-lang.org/browse/SI-7139) is the culprit.

**Comment by refried** [comment]
Same.
