### ISSUE TITLE
This just in from Fox News: Or in Cats is not right biased

### ISSUE THREAD

**Issue by bvenners** [non/cats#189]
Hi All,

I wanted to start a discussion around whether Or in Cats should be left or right biased. It is currently right biased, and the concern I have is there's already an Or out there that's left biased. Scalactic Or has been out for about a year and a half, and I'm concerned that if Cats comes out with an Or that's right biased, it will confuse folks. So I'd like to suggest you consider making it left biased, changing the name in Cats, or possibly using Scalactic's Or as a dependency.

There are good reasons on "both sides". I had a nice (but rather long) discussion with the scalaz folks about it (and a few other issues that you have yet to take up) here:

https://groups.google.com/forum/#!msg/scalaz/R-YYRoqzSXk/9pKpiUDf3wQJ

I did also do a talk at nescala recently where I talk about the left versus right subject:

https://thenewcircle.com/s/post/1704/comparing_functional_error_handling_in_scalaz_and_scalactic

So there's folks on both sides of the debate with useful comments. My main concern is that since there's an Or out there already that's left biased, it will add confusion if Cat come out with an Or that's right biased.

Discuss.

**Comment by refried** [comment]
I just thought it was because right was "right" and left was "sinister" (Latin).  Didn't know all of this about partially applied type constructor convenience.  I agree that Type Or Error reads more cleanly. *shrug*

**Comment by rossabaker** [comment]
I'm glad we're challenging the decisions of our various forebears in building this library.  However, I expect Cats users will be more familiar with -- and more often interoperate with -- `scala.Either` than `org.scalactic.Or`.  Even though `scala.Either` is unbiased, it established a convention of success on the right that I would not overturn lightly.

**Comment by tpolecat** [comment]
The convention is to assume partial application from the left (possibly because this is the easiest way to do it in Haskell) leaving the rightmost type parameter free. Scalaz `\/` is just one case of this; the `Functor` instances for `TupleN` are also right-biased. I guess there is no reason in principle why we couldn't bias to the leftmost parameter since partial application in Scala is equally irritating both ways, but I kind of lean toward consistency with the other functional languages unless there's a compelling reason to differ.

I have no problem renaming `Or` though ... what if we called it `\/`?

/me runs

**Comment by wedens** [comment]
I don't find `Type Or Error` more readable than `Error Or Type`. When reading this type it looks equivalent.

**Comment by rossabaker** [comment]
I am less attached to the name than the bias. I previously considered `Xor`, but never fell in love with `InclusiveOr` for a type isomorphic to `scalaz.\&/`, so I kept my mouth shut.

**Comment by ceedubs** [comment]
@rossabaker is `AndOr` more palatable than `InclusiveOr`?

**Comment by mpilquist** [comment]
I'm in favor of a left-biased `Or`. I agree with @rossabaker that early adopters of cats would be surprised by a left bias. However, one of the goals of cats is to bring functional programming to a larger audience. Anecdotally, when teaching Scalaz, I've seen the right-biased nature of various types confuse folks. I'm also fine with sticking with a right-bias if folks feel strongly about this.

I agree with @tpolecat that we should be consistent though -- `TupleN` instances, `State`, etc.

I'm not stuck on the name `Or` either. However, I do feel strongly about not using `\/`, which I consider to be a challenge to folks who think names are meaningful.

**Comment by mpilquist** [comment]
Oh, and I highly recommend everyone watch Bill's video above. It's interesting to reflect on what motivates each of us to contribute to cats in context of Bill's introduction.

**Comment by julien-truffaut** [comment]
I believe it doesn't matter for person new to fp if `Or` is left or right biased. However, it would rather keep `Or` right bias for consistency with other languages like Haskell. 

`\/` can be a symbolic type alias for `Disjunction`

**Comment by milessabin** [comment]
Would it help to use `||` instead of `\/` or `v`? It's naturally left biased and would allow us to piggyback on peoples intuitions about `||` on booleans.

**Comment by lvicentesanchez** [comment]
The convention for scala.Either is that Left is an error, Right is Success; given that Or is nothing more that a success biased Either, it make sense to keep consistency and make it right biased.

**Comment by travisbrown** [comment]
I don't think anyone would argue that `Option`'s `Some` should precede `None` (either in the sense of its `Ordering` instance or the order of the arguments on its `fold`), or that `::` should precede `Nil`—you start counting at zero. Keeping `Or` "lined up" with `Option`, `List`, etc. seems like as good a reason as any for right-biasing.

**Comment by mpilquist** [comment]
@milessabin `||` or even `|` is interesting. It's worth pointing out that `\/` and `||` typically represent *inclusive* disjunction in logic (Scalaz's `\&/`). Part of me wants a type operator `or` that's inclusive and another type operator `xor` that's exclusive, potentially along with `v` and `⊕` aliases. The lowercase signifies their use as a type operator and avoids clashing with scalactic.

**Comment by bvenners** [comment]
@travisbrown One of my goals of left-biasing Or in Scalactic was an attempt to be consistent with the standard library. What I thought was most relevant were Try and Future, both of which have a notion of success and failure. The fold method on those types puts the success function on the left and the failure function on the right.

By contrast, neither Option nor List is focused on error handling. Option can be used for an error result, but it is more often used to represent something that's simply optional, where not being there is not an error, just one of two possibilities. Option's fold method is curried and puts the "None" by-name in the first param list and the "Some" function in second second, but I think that's idiomatic since the None side is a by name. When there's only one function being passed, we usually put that at the end in a curried parameter list.

Either is also not focused on error handling, which is the whole reason I felt we should have an Or. As someone mentioned in this discussion, the actual API of either is quite "fair and balanced," not favoring either side. There's just one line in the Scaladoc documentation that suggests folks put errors on the right. That was an arbitrary choice probably inspired by the tradition of Haskell.

**Comment by travisbrown** [comment]
@bvenners But `transform` isn't really the same as `fold`, and in my experience it's pretty rare to see in normal usage (I also personally don't think it's very well designed, if only because `Try#transform` and `Future#transform` do such different things).

Related question: I've always found it kind of odd that Haskell's writer and state are `(a, s)` while its functor for tuples is right-biased. I agree that if we go left-biased on `Or` we need to go left on the instances for tuple, etc., as well, but where are we on state and writer? Does it matter?

**Comment by tpolecat** [comment]
Agree, I always expect `State` to be `s => (s, a)`. No idea.

**Comment by rossabaker** [comment]
I have one issue with @mpilquist 's proposal, but it's a greater problem in the status quo: the inclusivity of  `or` is ambiguous in common usage.  The exclusive type is going to be more common, and I'm fairly certain I'd expect `or` to be inclusive having already encountered `xor`.  I think it's an improvement overall.

@ceedubs ' `andOr` gets high marks for communicating intent, but has neither mathematical nor English tradition on its side.

**Comment by stew** [comment]
My gut tells me that a left bias is wrong, just to be in agreement with what I think is widespread convention, and consistency with scalaz and haskell.

I'm willing to not go completely nuclear on this before I have a chance to watch bvenners's talk as suggested by mpilquist, however :)

**Comment by tpolecat** [comment]
Consider `Either[A,B]` vs `Function1[A,B]` vs `EitherT[F[_], A, B]` vs `Kleisli[F[_], A, B]`. With right-biasing we can easily find the parameter that varies with the `Functor` instance because it is consistently the rightmost one (and the `Contravariant` instance, if any, is the leftmost parameter of kind *). With sporadic left-biasing this becomes needlessly confusing. I doubt the Scala world is prepared to start writing `A => B` as `Cofunction1[B, A]`.

**Comment by mpilquist** [comment]
@tpolecat That's a great argument.

**Comment by travisbrown** [comment]
I guess for me it comes down to the question of whether partial application is just about syntactic convenience. I personally feel pretty strongly that parameters that vary more should be more to the outside, whether they're types or values, and whether or not some particular language's syntax makes partial application convenient.

As @stew says, this is more a gut feeling than anything else. I really wish PL ergonomics were a thing that actually existed as a discipline.

**Comment by tixxit** [comment]
I like the lower-case type operator name idea, @mpilquist (eg. `A or B`)

**Comment by non** [comment]
I'm sort of ambivalent on the handedness question myself. I think @tpolecat's argument may be right -- it seems persuasive, I just need to think about it some more.

The one thing that bugs me is that in language we usually prefer to talk about the common case first, e.g. "Either Amazon sends you the *1977 Traveller boxed set* you ordered, or it refunds your money." If we planned to support `Coproduct2` through `Coproduct23` I would probably prefer to store the "useful part" on the left side.

**Comment by non** [comment]
Also, I consider this the nuclear option of type aliases:

```scala
type ∐[A, B] = Either[A, B]

def trySomething(...): Error ∐ Result = ...
```

http://en.wikipedia.org/wiki/Coproduct#Definition

**Comment by bvenners** [comment]
I just read through all the comments. It sounds as if cat-people are leaning more towards the right than the name Or. If cats picks a different name than Or, then that addresses my concern about user confusion.

@tpolecat your note about Function1 is interesting, because indeed Function1 is "right biased." I see the consistency benefit of always abstracting over the right hand type for Functors. But I think your point that, "I doubt the Scala world is prepared to start writing A => B as Cofunction1[B, A]." really highlights a difference in perspective here. I don't expect the Scala world at large is prepared to start using Functor very much at all, be from it scalaz, cats, Scalactic, or any other library.

It goes back to the question from my talk about designing for "us," meaning people who know about FP already, versus designing for "them," meaning people who don't (but are familiar with OO). My feeling was that Scalaz was firmly i the camp of being designed for "us," whereas I was trying to design for "them" in Scalactic. It sounds like cats may be more about designing for "us" as well, which is fine. And in that design context a right bias for Or (or whatever it ends up being called in cats) makes more sense to me.

**Comment by mpilquist** [comment]
Not sure where we are on this. How do folks feel about this proposal:

 - Define `or` and `xor` types, where `or` is inclusive and `xor` is exclusive. 
 - Type names and companions are lowercase, signifying their intended use as a type operator.
 - Constructors are `lor`, `ror`, `lxor`, and `rxor`.
 - Transformers are `OrT` and `XorT`.

**Comment by ceedubs** [comment]
Thanks for coming up with a concrete proposal, @mpilquist. I vote for proposal 3. I like the consistency and that newcomers won't potentially be confused by the lowercase type names of 1 and 2. However, I don't have strong opinions here and I'm okay with other outcomes.

**Comment by rossabaker** [comment]
Is there any precedent in the Scala community for a lowercase type operator?  It's cute, but I share @ceedubs' consistency concerns.

I prefer proposal 3, but am not sold on abbreviating Left and Right.  `rxor` gets me thinking of [warning: trigger word] reactive.

**Comment by julien-truffaut** [comment]
I also prefer upper case type but I am indifferent regarding `Ior` or `Or`

**Comment by mpilquist** [comment]
@rossabaker et al -- How do you feel about `Xor.left` / `Xor.right` and `Ior.left` / `Ior.right` for constructor names?

**Comment by mpilquist** [comment]
`left`/`right` constructors and `Left`/`Right` extractors are unambiguous as long as they aren't imported directly. I'm OK with this as I think it strikes a nice balance, though I've noticed some examples are importing `Or.LeftOr` and `Or.RightOr` currently.

**Comment by ceedubs** [comment]
@mpilquist I like your `Xor.left` et al suggestion.

**Comment by rossabaker** [comment]
I like `Xor.left` et al, too.

**Comment by rossabaker** [comment]
Any lingering objections to the `Xor.left` proposal?

**Comment by mpilquist** [comment]
If there are no further objections, I'll put together a PR for this.
