### ISSUE TITLE
Consistency in names of duals (and other prefixes)

### ISSUE THREAD

**Issue by japgolly** [non/cats#192]
There is inconsistency in capitalisation the names of filenames, object/class/traits and methods of duals.
Eg. `CoFlatMap`, `Comonad`, `def coflatMap`.

I think a consistent strategy should be chosen early to save having to rejigg everything later.

Such a strategy should probably also bind other prefixes like `Bi` and possibly `Pro`.

**Comment by tpolecat** [comment]
Agree. I vote for all such prefixes to *not* trigger camelcasing, i.e., `Bifoldable`, `CoflatMap`, `bimap`.

**Comment by mpilquist** [comment]
Another +1 on no camel casing.

**Comment by non** [comment]
Yes, I agree (and apologize for the initial inconsistency).

The literature capitalizes them as *Comonads*, *Cofunctors*, *Bifunctors*, etc. so I think we should follow that style.

**Comment by rossabaker** [comment]
Is this the place to discuss what we do when the duals have their own well known names (e.g., Extend, Extract)?

**Comment by fthomas** [comment]
`CoFlatMap` is the only offender right now, right?

**Comment by refried** [comment]
Is FlatMap ok?

**Comment by non** [comment]
@fthomas Yes, I think that's right.

@refried Yes, I think the basic convention is that a method called `flatMap` should correspond to a class called `FlatMap`, and the same with `coflatMap` and `CoflatMap`.

**Comment by rossabaker** [comment]
I can take this one.  I have `CoflatMap` on the brain right now.

**Comment by japgolly** [comment]
I just searched as well and `CoFlatMap` is the only outlier. #202 should do it.
