### ISSUE TITLE
Add Semigroup and Monoid laws/tests

### ISSUE THREAD

**Issue by ceedubs** [non/cats#196]

**Comment by lvicentesanchez** [comment]
I will take care of this one.

**Comment by fthomas** [comment]
@ceedubs `Semigroup` and `Monoid` are coming from algebra. Why do we need tests for them in cats? Surely there are tests for them in algebra?

**Comment by non** [comment]
Yes, Algebra already exports laws for these as well.

**Comment by ceedubs** [comment]
Oops sorry. We should check these laws for our instances.

**Comment by lvicentesanchez** [comment]
Added SemigroupK/MonoidK instead.

**Comment by fthomas** [comment]
@ceedubs, can we close this now that #198 is merged?

**Comment by ceedubs** [comment]
:+1:
