### ISSUE TITLE
Add doc for FreeMonad (& FreeApplicative)

### ISSUE THREAD

**Issue by mandubian** [non/cats#197]

**Comment by mandubian** [comment]
I've started writing something on it

**Comment by non** [comment]
@mandubian Do you still  have things you are working on for this bug? Should it be closed? Is there a status update we can post here?

**Comment by mandubian** [comment]
I have published docs for FreeMonad in another PR and couldn't find time to work on FreeApp doc.
So you can close it for now, we'll open a new one later

**Comment by non** [comment]
Ok, I'm closing this issue in favor of #321
