### ISSUE TITLE
Add Alternative type class

### ISSUE THREAD

**Issue by mpilquist** [non/cats#212]
An `Alternative` is an `Applicative` and a `MonoidK`, where the monoid operations interact with the applicative operations according to some laws -- known in Scalaz as an [ApplicativePlus](https://github.com/scalaz/scalaz/blob/689bb4bf2603f2fd407ff4450cddc77e4ff15e7a/core/src/main/scala/scalaz/ApplicativePlus.scala).

For reference, Structures defines [Alternative](https://github.com/mpilquist/Structures/blob/9b35e827f7d83cc73a2715bd293e8712e2c42675/core/shared/src/main/scala/structures/Alternative.scala). It also defines [AlternativeLaws](https://github.com/mpilquist/Structures/blob/9b35e827f7d83cc73a2715bd293e8712e2c42675/laws/src/main/scala/structures/laws/AlternativeLaws.scala).

Miscellaneous notes:
 - `Alternative`s compose -- `Alternative[F] compose Alternative[G]` yields `Alternative[F[G[?]]]`.
 - The derived `many` method should return an `F[Nel[A]]`.
 - The `asum` method defined on Structures's version should be omitted, as it really belongs on `MonoidK`.

**Comment by ceedubs** [comment]
Fixed by #225

**Comment by refried** [comment]
Btw, why is it called `Alternative`?
