### ISSUE TITLE
hook up scalatest === to cats' eq

### ISSUE THREAD

**Issue by stew** [non/cats#219]
spoke @bvenners:

Not sure if you're aware, but you can teach ScalaTest's === to look for Cat's Eq instances, so the type checkiung comes from the presence of a Cats Eq instance but you still get decent error messages from ScalaTest when assertions fail.
I demoed how to do this in scalaz and spire a while back here: 

https://github.com/bvenners/equality-integration-demo

**Comment by ceedubs** [comment]
I'm going to give this a try.

**Comment by Daenyth** [comment]
Compiling still fails when you `import cats.implicits._`, due to ambiguous implicits.
