### ISSUE TITLE
Test `Traverse` and `Foldable`

### ISSUE THREAD

**Issue by rossabaker** [non/cats#224]
1. Need laws for `Traverse` and `Foldable`.
2. Need discipline tests for the same
3. Fill in tests for their instances.

**Comment by woparry** [comment]
I will add these tests.

**Comment by woparry** [comment]
Pull request submitted, including bugfixes for List.traverse and Vectore.traverse.

**Comment by woparry** [comment]
#328

**Comment by woparry** [comment]
#328 was the PR for this - this issue should be closed (sorry for muddying up the issue tracker).
