### ISSUE TITLE
`OrT` monad transformer for `Or`

### ISSUE THREAD

**Issue by adelbertc** [non/cats#229]
I often work a lot with `scalaz.DisjunctionT/EitherT`, specifically in the form of `DisjunctionT[Task, Error, A]`.

**Comment by ceedubs** [comment]
I definitely will want this as well. I think the main question is where it should go. As far as I know, we don't quite have our module structure figured out yet.

**Comment by rossabaker** [comment]
I think it goes in data.  A separate transformers module would make it awkward to create any data types as an alias to a monad transformer applied to `Id`, should we ever follow that Scalaz pattern.

As the probable precedent setter for transformers, there's more to discuss:

* Is the `*T` convention something we want to continue?  I understand and expect it now, but I didn't when I came to Scalaz without a Haskell background.  I don't have a better suggestion, other than to be sure we explain it.

* Does anybody want to argue on behalf of covariance?

**Comment by rossabaker** [comment]
Speaking of transformer conventions, there's also a `StateT` baking on #122.

**Comment by lvicentesanchez** [comment]
I would find it weird if it didn't end in `cats.data`. And regarding the naming convention `*T` seems reasonable to me, I actually have serious troubles to find a better name... maybe `*Trans`?

**Comment by alexknvl** [comment]
Won't changing names make it harder for people to find documentation? At least with standard naming convention you can always find Haskell / Scalaz docs. Searching `StateTrans` on Google gives you no relevant results.

**Comment by rossabaker** [comment]
I've made my peace with the `*T` suffix.  `*Transformer` feels too long, and I can't think of anything else that improves the standard enough to merit diverging from the standard.

**Comment by mpilquist** [comment]
I'm going to start on this tonight. Speak up if you've already started working on it.

**Comment by rossabaker** [comment]
It's going to be `XorT` now, right?

**Comment by mpilquist** [comment]
Right -- wip branch is here: https://github.com/non/cats/commit/edac355a086597b020e3d3621502a37f9626ffb1

**Comment by mpilquist** [comment]
What do folks expect the `===` method on `XorT[F, A, B]` to return? Scalaz's `EitherT` returns an `F[Boolean]`. I think folks typically expect to get a `Boolean` back though. The wip link above does the latter but I can change to the former if folks object. The same question exists for `compare`, `partialCompare`, and `show`.

**Comment by ceedubs** [comment]
@mpilquist has submitted PR #287 for this. I think that one is close to getting merged, so I'm going to close this and we can continue any further discussion there.
