### ISSUE TITLE
Can you comment on FlatMap?

### ISSUE THREAD

**Issue by johnynek** [non/cats#3]
Why would we want that but not Monad? Are there examples where we can implement one but not the other?

**Comment by non** [comment]
So, the design comes from [semigroupoids](https://hackage.haskell.org/package/semigroupoids). (See `Bind`).

I'm honestly not 100% sure which instances have `FlatMap[F]` but not `Monad[F]` -- there are definitely places where you only need `flatMap` (e.g. `Kleisli`). I'll try to investigate.

**Comment by non** [comment]
@mpilquist mentions that `Map[K, ?]` as an example, where you can't implement `pure` (which key would you use?) but you can implement `flatMap`.

**Comment by ceedubs** [comment]
I think `Map[K, ?]` is a strong argument for keeping `FlatMap` as a separate type class. @johnynek what do you think?

**Comment by mpilquist** [comment]
Similarly, `Apply` is an `Applicative` without `pure`. I think it is easier to see use cases for `Apply[Map[K, ?]]`:

```scala
scala> val m = Map(1 -> 1, 2 -> 2, 3 -> 3)
m: scala.collection.immutable.Map[Int,Int] = Map(1 -> 1, 2 -> 2, 3 -> 3)

scala> val n = Map(1 -> 1, 3 -> 9)
n: scala.collection.immutable.Map[Int,Int] = Map(1 -> 1, 3 -> 9)

scala> Apply[Map[Int, ?]].map2(m, n)((x, y) => y - x)
res0: scala.collection.immutable.Map[Int,Int] = Map(1 -> 0, 3 -> 6)
```

**Comment by xuwei-k** [comment]
https://github.com/scalaz/scalaz/blob/v7.1.0/core/src/main/scala/scalaz/UnwriterT.scala#L106
https://github.com/scalaz/scalaz/blob/v7.1.0/core/src/main/scala/scalaz/UnwriterT.scala#L6

`scalaz.UnwriterT` is a `Bind`. but not `Monad`.

**Comment by xuwei-k** [comment]
`type x[a] = OneAnd[({type y[b] = OneAnd[List, b]})#y, a]` is a `Bind`. but not `Monad`

**Comment by johnynek** [comment]
Sounds good all. Thanks for the examples.

**Comment by ceedubs** [comment]
@johnynek do you want to go ahead and close the issue then?
