### ISSUE TITLE
Monoid[Double] and Monoid[Float] are incorrect

### ISSUE THREAD

**Issue by xuwei-k** [non/cats#301]
https://github.com/xuwei-k/cats/commit/6dbad2ddff10

**Comment by ceedubs** [comment]
I believe this was a conscious decision by @non with the assumption that people generally know about the gotchas with floating point arithmetic but still want to be able to add floats and doubles. Is that an accurate assessment, @non?

It seems to me like the options are either:
1) Move these into alleycats (but I suspect people using algebra without Cats still want these)
2) Be explicit about the fact that we know this is naughty but we are doing it anyway. In this case we should add some documentation about this.

I could see an argument that the blame lies as much with the `Eq` instances as it does with the `Semigroup` and `Monoid` instances.

**Comment by xuwei-k** [comment]
I don't mean it.

https://github.com/non/cats/blob/682a39423bca461ffb37a0ff7d12b2a6fda7099e/core/src/main/scala/cats/std/anyval.scala#L97-L98

> ```scala
def combine(x: Float, y: Float): Float = x + y
def empty: Float = 1F
> ```

the `combine` defined by `+`, but `empty` is `1F`.
I think `empty` should be `0F` or `def combine(x: Float, y: Float): Float = x * y`

**Comment by ceedubs** [comment]
@xuwei-k oh wow thanks for pointing that out. I can't believe we let that go for so long! I'll submit a fix.
