### ISSUE TITLE
Automatically publish snapshots (or versioned by Git hash)

### ISSUE THREAD

**Issue by non** [non/cats#317]
Pretty much what it sounds like. It would be good to automatically do this so that folks can quickly try out the newest and shiniest parts of Cats.

I have historically been against publishing `-SNAPSHOT` builds, but they are relatively easy, and have the nice property of not taking up a ton of space. I've heard of `sbt-git` but haven't used it yet, so that might be an alternative that would produce stable versions to depend on.

**Comment by non** [comment]
It sounds like @InTheNow is going to look into this.

If people have strong feelings about `-SNAPSHOT` versus git-hashes, speak up now! :)

**Comment by dwijnand** [comment]
Speaking as a non-maintainer of cats, my preference is for git hashes.

It would be easier to make a case for it if there were at least 1 release (tag) of cats, as one nice way to version builds is using `git describe` (which `sbt-git` supports) which amounts to:

> The version will be the last tag + number of commits since tag + short hash

**Comment by non** [comment]
@dwijnand Interesting. I think we might be getting close to a 0.1 release if we can improve our documentation/test coverage.

**Comment by rossabaker** [comment]
Would these untagged releases go to Maven Central, or is that a holy place for tagged builds?

**Comment by dwijnand** [comment]
Shapeless pushes to Sonatype snapshots, but perhaps bintray would be faster and/or easier.

**Comment by InTheNow** [comment]
I copied some comments on topic to https://github.com/w3c/banana-rdf/pull/240. There is some b-rdf noise there, main points are that Maven 3 and Artifactory have (I think) already addressed these issues and hence, if possible, it would be best to use these rather than "role our own".

**Comment by InTheNow** [comment]
Further to my previous link from 06.03.2105, I've google'd some more on having auto-time stamped SNAPSHOTS as per Maven3:

- [SBT doesn't honor Maven's uniqueVersions #1322](https://github.com/sbt/sbt/issues/1322)
- [sbt-maven-resolver: Use Aether for resolving maven dependencies #1793](https://github.com/sbt/sbt/pull/1793)
- [sbt release 13.8 adds ](https://github.com/sbt/sbt/releases/tag/v0.13.8)

So whilst I have tried this, it _could_ give us the required solution.

@eed3si9n  and @dwijnand You are both cited on the release, any inputs on this, please? And for @dwijnand in particular, would this cover your needs, as I note that you expressed a git preference?

**Comment by dwijnand** [comment]
I apologise up front, but I had real difficulty understanding the details in that banana-rdf pull request.. but I'm actually interested, why you did you have to rollback using git hashes?

Even if there's prior art to making `-SNAPSHOT`s auto-timestamp, I would still go with something like `sbt-git`'s `enablePlugins(GitVersioning)`, as I find it useful to know the tag distance and commit SHA.

Then if updating that reference became a burden I would try something like [sbt-updates](https://github.com/rtimush/sbt-updates) to help me update it.

**Comment by InTheNow** [comment]
> why you did you have to rollback using git hashes

We didn't _have_ to, rather I wanted to. The main point I guess I'm trying to get over is that the SNAPSHOT mechanism that people _think_ there is actually has actually changes; it's just that ivy has not caught up.

So in maven3, they always have a timestamp added for uniqueness. And is it is an in built feature, tools (other than ivy) know what to do with it, without having to explicitly update project files.

So, in a well setup environment, the end user can specify how _they_ want to work with "snapshots" eg:

- always look for an update
- look daily
- never look ( ie freeze local version)
- use specific version

As an example of tools that already do this is eclipse.

As a suggestion for a route forward, why don't I try and set up such as system in Cats DEV environment so we can all have a look for real? Oh, and it''s not that I am against the git approach, I just think a more universal solution exists

**Comment by InTheNow** [comment]
Here is a [random example](https://oss.sonatype.org/content/repositories/snapshots/io/airlift/dbpool/0.110-SNAPSHOT/)

`dbpool/0.110-SNAPSHOT` is one version snapshot, but there are 5 actual versions stored there. [The pom](https://oss.sonatype.org/content/repositories/snapshots/io/airlift/dbpool/0.110-SNAPSHOT/maven-metadata.xml) is accessed via `dbpool/0.110-SNAPSHOT` and points to the latest version, but the previous ones are available explicitly.

**Comment by dwijnand** [comment]
Ah, I see, so you're still depending on cats `0.1.0-SNAPSHOT`.

For various reasons, including repeatable builds and for `git bisect`, I would prefer using a stable identifier, so I would start by trying out cats version `0.1.0+3-1234abcd`, and then 3 days later, when there's some interesting change in cats I want to try out, I update it to `0.1.0+7-5678efgh`.

You could say perhaps I don't want automatic "snapshots", but more automatic pre-releases (say on every pull request merge, or maybe just nightly).

**Comment by InTheNow** [comment]
> Ah, I see, so you're still depending on cats 0.1.0-SNAPSHOT

Ahh - but not necessarily, that's the point. In fact we have _both_ cases available: Examples:

- user @inthenow uses `0.1.0-SNAPSHOT` and will get the "automatic" one
- User  @dwijnand thinks that is a bad idea so uses  `0.1.0-SNAPSHOT-20150518.223019-1` and has a stable build, no matter if new snapshots are done. Then, and then 3 days later, when there's some interesting change in cats he wants to try out, he update it to  `0.1.0-SNAPSHOT-20150521.223019-2`

**Comment by dwijnand** [comment]
Ah, sweet.

So now the question is between:
* A system that includes tag distance and exact SHA, but requires a little work (tooling) to later update version
* A system that is timestamp only, but which you can configure when to update (always/daily/never).

**Comment by InTheNow** [comment]
> Ah, sweet.

:)

System b) that you mention is maven 3, and now part of sbt since 13.8 . So that would be my recommendation, _by far_

If you want the first, couldn't this be achieved artificially by a generic plugin seeing that there is an exact timestamp? ie you get the git info based on time stamp?

**Comment by non** [comment]
My sense is that (b) is easier for us. I worry that (a) would be a lot easier for users if we set it up. But maybe if we document how to use timestamped snapshots (and ensure that old timestamped snapshots aren't clobbered by newer ones) then maybe things are OK?

A totally separate issue is if Sonatype will store a large number of timestamped snapshots? If not, how quickly will they be deleted?

(I'm sorry for raising all these issues. I'm new to this process and just trying to think it through.)

**Comment by InTheNow** [comment]
> how to use timestamped snapshots

Already documented in sbt, we can always add our own introduction

> old timestamped snapshots aren't clobbered by newer ones

Sonatype will not allow this

> if Sonatype will store a large number of timestamped snapshots?

By default-ish, yes, as timestamped snapshots are recommended

> quickly will they be deleted

Not sure if this can be set up within sonatype or we need to do it. will look int that

**Comment by InTheNow** [comment]
> if Sonatype will store a large number of timestamped snapshots

See [Remove Snapshots from Repository in](https://books.sonatype.com/nexus-book/reference/scheduled-tasks.html).

**Comment by non** [comment]
Right, that makes sense.

However, I wonder whether the task makes sense. I think part of the request for "versioned" snapshots was that they would be stable and permanent (so that N months down the line people's projects would still work). If we are deleting the timestamped snapshots, that means those dependent projects will still break N months out.

Maybe we should use un-timestamped snapshots in the "normal way" and also periodically publish stable milestones once a week/month/so-often?

**Comment by InTheNow** [comment]
from the docs "A value of -1 indicates that all snapshots should be preserved." So that would suffice.

> Maybe we should use un-timestamped snapshots in the "normal way"

In fact, as of maven 3_all_ snapshots are time stamped but we can see this when we start using it.

**Comment by non** [comment]
OK, great. Sorry for my scattered thoughts on this.

It seems like you've got a handle on it, so I'll be quiet and see what the PR looks like. Thanks! :)

**Comment by eed3si9n** [comment]
For untagged builds, my preference would be to:

1. use git SHA versioning
2. make a maven-snapshots repository on Bintray and publish to it
3. sync artifacts to both [JCenter][1] and [Maven Central][2]

sbt did add [Maven resolver plugin][3], but it's still experimental, and I see it more as a compatibility glue for legacy rather than a way forward. @jsuereth is the author for both sbt-git and the plugin. We can ask what he thinks. Another thing is that I don't know if Sonatype OSS is going to let you keep older snapshots, and JCenter is probably faster to resolve (uses Amazon's CDN).

  [1]: https://bintray.com/docs/usermanual/uploads/uploads_includingyourpackagesinjcenter.html
  [2]: https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html
  [3]: http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#Maven+resolver+plugin

**Comment by InTheNow** [comment]
Hmm:

Bintray does not support snapshots, nor does JCenter.  What they do provide, via Artifactory, is [OJO](http://www.jfrog.com/confluence/pages/viewpage.action?pageId=26083425) "Host my snapshot build artifacts on the OSS Artifactory at https://oss.jfrog.org" See [example](http://oss.jfrog.org/simple/oss-snapshot-local/co/freeside/betamax/betamax-core/2.0-SNAPSHOT/)

The maven snapshots here are also timestamped, even if you don't want them to be. 

So yes,  there is a choice between Sonatype and JFrog's  OSS Artifactory, but both use Maven 3 timestamps for snapshots.

"Maven's support for "unique versions" was deprecated in Maven 2, which reached EOL in February 2014, and definitely disabled in Maven 3. " - [sbt](https://github.com/sbt/sbt/issues/1322)

**Comment by InTheNow** [comment]
But... as I really am not _that_ opinionated on the subject - I wonder if we can do all three, that is in addition to https://github.com/non/cats/issues/317#issuecomment-104917125:

- also add `git description` info to additional jars as an extra pom classifier or similar

**Comment by InTheNow** [comment]
@non To get this to work, we need a tag for git to work from. For this I added a tag "v0.0.0" and the initial commit, so please can you do this on master as well?

```
git  tag -m "v0.0.0" v0.0.0 9d1837e20a89c99c174723a2f112d84507b9ebdb
```

**Comment by ceedubs** [comment]
Adding cats-0.1.0 milestone per @milessabin's recommendation. If people feel that this should not be a blocker for release, we can consider removing it from the milestone.

**Comment by InTheNow** [comment]
@non don'f forget https://github.com/non/cats/issues/317#issuecomment-111186137 :

To get this to work, we need a tag for git to work from. For this I added a tag "v0.0.0" on the initial commit, so please can you do this on master as well?

`git  tag -m "v0.0.0" v0.0.0 9d1837e20a89c99c174723a2f112d84507b9ebdb`

**Comment by ceedubs** [comment]
I'm not sure if this is related to https://github.com/non/cats/issues/317#issuecomment-113922974, but the build is now failing with:

> [error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org].
java.io.IOException: Access to URL https://oss.sonatype.org/content/repositories/snapshots/org/spire-math/cats_2.11/0.1.0-SNAPSHOT/cats_2.11-0.1.0-SNAPSHOT.pom was refused by the server: Unauthorized

**Comment by InTheNow** [comment]
As well as the the tag, this needs appending to build.sbt (from https://gitter.im/non/cats?at=5579ab11813c577e1cf60c66)

```scala
// For Travis CI - see http://www.cakesolutions.net/teamblogs/publishing-artefacts-to-oss-sonatype-nexus-using-sbt-and-travis-ci
credentials ++= (for {
  username <- Option(System.getenv().get("SONATYPE_USERNAME"))
  password <- Option(System.getenv().get("SONATYPE_PASSWORD"))
} yield Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", username, password)).toSeq

```
