### ISSUE TITLE
Set up code coverage

### ISSUE THREAD

**Issue by non** [non/cats#318]
It would be nice to see how good our tests are.

I've used [scoverage](https://github.com/scoverage) a bit so maybe it's worth it to start there.

It would be *really* fancy to have Travis automatically calculate code coverage for us. One site I've seen that does this is [https://codecov.io/](https://codecov.io/). The Miniboxing project is using this right now and it seems interesting.

**Comment by non** [comment]
It sounds like @InTheNow is going to look into this.

**Comment by InTheNow** [comment]
@non Although technically unrelated to sjs, are you OK if i do this on that branch? As we have code that is compiled twice, tested once (twice in the future) I would like to set things up with these scenarios already considered

**Comment by non** [comment]
Sure, I am fine with that.

Worst-case, you or I can port the code from this branch to master if we feel like we need it sooner.
