### ISSUE TITLE
Some github.io docs rendering issues

### ISSUE THREAD

**Issue by refried** [non/cats#323]
I noticed a few places in freemonad.html where the markup isn't being displayed correctly:

1. "Run your program stack-safe" is "6." in the .md and "1." in the .html.  In fact, it looks like all of the numbered sections become "1." in the html.

2. At least one tut block is not rendering correctly; search for "// Pure computation";  I can't tell why it isn't.

**Comment by fthomas** [comment]
It seems that this has been resolved in the meantime.

Please reopen if there are still rendering issues.
