### ISSUE TITLE
Fold cats.std into the core project

### ISSUE THREAD

**Issue by non** [non/cats#333]
I think we should move everything from the `std` project into `core` (preserving the `cats.std` namespace) and then get rid of the `core` project.

For a more detailed rationale, see discussion attached to #258.

What do you all think? If I don't hear anyone else pushing to defend the distinction I'll prepare a PR as soon as I can.

**Comment by refried** [comment]
Wait, move everything into `core` and then get rid of `core`? :)

**Comment by non** [comment]
No, no, I want to keep the other separations (free, state, and so on).

**Comment by woparry** [comment]
I'm not so sure about this - the separation felt clean to me, and kept core relatively uncluttered (it didn't contain any instances).
Have we considered going the other way - breaking things up into much more granular modules, and explicitly declaring their dependencies and pulling in the things you need to work with them?

Under such a model, we'd have dependency diagrams like:

ApplicativeTypeclass              >   TraverseTypeclass
 v                                                  v
(List, Option, etc)Applicative        (List, Option, etc)Traverse
 v                                                  v
Applicative                                   Traverse

Then those who want to wholesale import everything needed to work with Traverse will just import the Traverse module, but we can declare much more minimal dependencies for typeclasses etc - and in particular, avoid referencing stdlib types in the typeclass definitions.

**Comment by non** [comment]
That's an interesting suggestion.

In projects like Spire, that wouldn't be ideal, since often you find yourself working with a concrete type (e.g. `Long` or `Double`) and want to import *all* the functionality Spire provides for that type. But it could work in Cats I suppose.

So in your scheme if I wanted to import instances for `Applicative[List]`, `MonoidK[List]`, and `Traverse[List]`, would I have to use three imports? How would that work?

(Also, to be clear, I still want to keep the `cats` namespace clear -- the instances would still live inside the `cats.std` namespace as they do now.)

**Comment by woparry** [comment]
You'd need separate imports for at least all non-derivable instances - hopefully you going import Traverse and also get Foldable, for example.

The alternate organization where you can get all instances for a type is also interesting; in theory that could also be provided (ie. via a separate set of modules with dependencies like ListApplicative -> ListInstances <- ListTraverse etc).

My worry is mainly that this is a step towards everything becoming a big ball of mud (which is kinda how I feel about scalaz).

**Comment by non** [comment]
I agree that I'm worried about a big ball of mud, and heartened that you liked the previous split.

How do you like the current design? Right now, we've corralled instances into objects like `cats.std.list`, `cats.std.map`, and so on. In a few very cases in core we have instances (right now just for `Id[_]` and for type classes defined in Algebra).

**Comment by julien-truffaut** [comment]
:+1:  for merging `std` into `core`, the two modules have the same dependencies, `std` will still be in its own package and it means we can use `std` instances in typeclasses default implementation.

**Comment by woparry** [comment]
Yes - actually, #107 is making me think about whether we want to have default typeclass implementations at all (I assume we're taking about things like filling in the implementation of map given flatMap).

In most cases the default implementation of foldLeft/foldRight in terms of traverse is awful for performance/laziness/etc.

Why even bother with it? Why not leave them all abstract?

It should be straightforward for people to write their own implementations of these in the typeclass instances, and not doing so is arguably wrong.

We have the laws to make sure that the implementations for map/flatmap/etc are consistent.

**Comment by woparry** [comment]
Also: regarding "modules still being separate" - one consequence of moving data into core is that data things are starting to show up on changes to std - see my comment on #304. Removing the module-level between std and core will make this worse.

**Comment by non** [comment]
@woparry I agree that in my experience one almost always wants to override all the methods defined by a type class. I've thought about a design where the typeclass itself is totally abstract, but then has one (or more) traits which provide defaults for users who want a terse definition (or for whom defaults are fine).

**Comment by woparry** [comment]
That sounds reasonable, especially if the default implementations are in a separate (optional) module.

**Comment by InTheNow** [comment]
Perhaps also of interest, from scala.js world -  https://github.com/non/cats/issues/349: Consider fine-granularity of typeclass instances

**Comment by non** [comment]
@woparry So having thought about this over the last couple of weeks, I think you've convinced me that default implementations on type classes should be optional (i.e. not built-in). However, I am starting to think that `std` instances should be folded into `core`. There are a few reasons for this:

1. It creates a model where `core` includes the relevant std instances and syntax classes for structures it provides. This generalizes well for other modules like `free`, `state`, and so on.
2. It removes the temptation to define custom data types just so that their instances are available. For example, `OneAnd`'s instances are already available in `core`.
3. Often we want to define a particular data type in terms of a more general one. For example, `State[S, A]` is defined in terms of `StateT[Trampoline, S, A]`. This process can get hairy when instances for types like `Function0` aren't available.

**Comment by adelbertc** [comment]
"std project into core (preserving the cats.std namespace) and then get rid of the core project" - what would the new core project be called?

**Comment by ceedubs** [comment]
@adelbertc I'm guessing that @non meant to type "get rid of the std project".

**Comment by adelbertc** [comment]
Done: https://github.com/non/cats/commit/6f282646db6facdb138a031c63219fd7e2e5ec15
