### ISSUE TITLE
Consider adding a MonadError type class

### ISSUE THREAD

**Issue by non** [non/cats#338]
EDIT: The consensus seems to be that a `MonadError` type class, a la Scalaz, is preferrable.

Haskell's monad typeclass has historically had a `fail` method.

[This proposal](https://github.com/quchen/articles/blob/master/monad_fail.md) proposes that Haskell introduce a `MonadFail` class to distinguish monads that have a sensible failure state from ones that don't.

Cats has never had a `fail` method. Should we add a type class that supports it? The proposal argues that `cats.MonadFail` could be useful independent of `cats.MonadCombine`.

**Comment by adelbertc** [comment]
I'm not sure how I feel about `MonadFail` given the `String`-iness of `String -> m a` but I would be very interested in something like `MonadError`.

**Comment by ceedubs** [comment]
I agree with @adelbertc. I don't see any reason to limit to String when we can abstract over the error. `MonadError` in scalaz seems to do a pretty good job of abstracting over error types for things like Future (where the error is always `Throwable`) but also for things like `Xor`, where the error type can vary.

**Comment by non** [comment]
This all sounds fine. Let's reframe this issue to be about `MonadError` then.

**Comment by non** [comment]
Closed in favor of #340
