### ISSUE TITLE
`mtl`-esque type classes

### ISSUE THREAD

**Issue by adelbertc** [non/cats#340]
https://hackage.haskell.org/package/mtl

I've primarily found use in `MonadError` that allows you to `handleError: F[E, A] => (E => F[E, A]) => F[E, A]` and `raiseError: E => F[E, A]` - useful when handling `XorT`.

Other ones I can perhaps see as useful are `MonadState`, `MonadReader`, and `MonadWriter` (maybe not this one since Cats doesn't have a `Writer` (yet)).

**Comment by ceedubs** [comment]
@travisbrown also [mentioned](https://github.com/non/cats/issues/314#issuecomment-103958495) the usefulness of `MonadState`.

I haven't really worked these type classes into my code yet, but they do seem like they could be helpful.

**Comment by adelbertc** [comment]
`MonadError` PR here: https://github.com/non/cats/issues/340

**Comment by adelbertc** [comment]
So we've got `MonadError` now - what do folks think about `MonadState` and `MonadReader` (or any other of the [mtl type classes](https://hackage.haskell.org/package/mtl) ) ?

**Comment by adelbertc** [comment]
All three are merged!
