### ISSUE TITLE
non-compiling test not caught by CI?

### ISSUE THREAD

**Issue by refried** [non/cats#350]
`tests/src/test/scala/cats/tests/ConstTests.scala` doesn't compile as of 0da98ce.

Is the `tests` project somehow not included in the CI process?  Main page says build is passing.

```
[error] /Users/arya/opensource/cats/tests/src/test/scala/cats/tests/ConstTests.scala:31: value eqv is not a member of algebra.laws.OrderLaws[cats.data.Const[Map[Int,Int],String]]
[error]   checkAll("Const[Map[Int, Int], String]", OrderLaws[Const[Map[Int, Int], String]].eqv)
[error]                                                                                    ^
[error] /Users/arya/opensource/cats/tests/src/test/scala/cats/tests/ConstTests.scala:32: could not find implicit value for parameter A: algebra.PartialOrder[cats.data.Const[scala.collection.immutable.Set[Int],String]]
[error]   checkAll("PartialOrder[Const[Set[Int], String]]", OrderLaws[Const[Set[Int], String]].partialOrder)
[error]                                                                                        ^
[error] two errors found
```

**Comment by travisbrown** [comment]
This is probably just SBT not updating the Algebra snapshot. Can you try again after `sbt update`, and if that doesn't work try one more time after nuking the relevant directories under `~/.ivy2`?

**Comment by adelbertc** [comment]
These were added by me and require the latest SNAPSHOT of `algebra` - I had to delete the `algebra` directories in `~/.ivy2/cache/org.spire-math` for it to work.

**Comment by refried** [comment]
Yeah I guess that was it.  Do we want to do anything to pinpoint the versions we're dependent on, or is this good enough?

**Comment by ceedubs** [comment]
@refried has this been a problem for you since cats stopped depending on a snapshot version of algebra? If not, do you think we are okay to close this issue?

**Comment by refried** [comment]
Sorry for disappearing. Okay to close this issue I think.
