### ISSUE TITLE
Release candidate

### ISSUE THREAD

**Issue by ceedubs** [non/cats#355]
I am guilty of being a perfectionist and never feeling like my work is ready to be released. I want to make sure we avoid the same mistake in Cats.

Here is my proposal:

1. Collect feedback on what people think currently prevents Cats from being release-ready. You can leave comments on this issue with items you think should be considered as potential blockers.
2. Make sure all of these items are documented via GitHub issues and a "release-blocker" tag is applied to them.
3. Once a query for the "release-blocker" tag returns no issues, let's kick off a release candidate build!

**Comment by rossabaker** [comment]
:+1:. I would also suggest that versions are relatively cheap while `majorVersion == 0`.  For all the excellent work on snapshots and git-described builds, an 0.x is going to invite even more people in for a test drive.  release-blockers should have a good reason they can't wait for 0.{x+1}.

**Comment by milessabin** [comment]
:+1: ... we should avoid letting the best be the enemy of the good.

**Comment by ngbinh** [comment]
if this https://github.com/non/cats/issues/18 is done then we will definitely jump on the bandwagon.

**Comment by InTheNow** [comment]
re release blocker - why not just create a cats 0.1 milestone and add the issues there? eg [shapeless-2-3.0](https://github.com/milessabin/shapeless/milestones/shapeless-2.3.0). Of course, a generic "blocker" label could also be used in addition to the milestone. 

Based on feedback I've had from others, the No.1 blocker - by a very wide margin - is documentation, followed by #18.

The reason for both being blockers is that if they are _not_ there, people will look once, say "yeah, just the same as XYZ" and not look again.

**Comment by ceedubs** [comment]
@InTheNow I wasn't aware of GitHub's Milestone feature. I like your suggestion. Let's go with that unless someone brings up a compelling reason not to.

I agree regarding documentation. I would like to see #157 completed before a release.

**Comment by ceedubs** [comment]
I created a [cats-0.1.0 milestone](https://github.com/non/cats/milestones/cats-0.1.0). Currently it's empty, but I'll add issues to it as we get more feedback.

**Comment by refried** [comment]
Maybe a dumb quesiton, but have any of us integrated cats into a real project in place of scalaz?  I keep trying but then backing off.  In particular, State + Lens support is what I get stuck on, but I suppose that would require a new project and new worms?

**Comment by non** [comment]
@refried I agree about State.

As far as lenses go: my initial feeling had been that we should encourage folks to use Monocle for lenses. Is that a bad plan? What would we need to do to scratch your itch? Do we need need a *monocles for cats* integration project?

**Comment by InTheNow** [comment]
https://github.com/non/cats/issues/349#issuecomment-112071369 refers to a scalajs project that uses scalaz state and Monocle....and not much else :stuck_out_tongue_winking_eye:

**Comment by mdedetrich** [comment]
I think we need to release some sought of preview (either a Milestone or Release Candidate) so that libraries can at least start contemplating/designing for cats. I think there is a lot of momentum for people to move to cats (I want to do this as well, wan't to start replacing `scalaz` with `cats` in our project), but it feels off if the project continuously feels like its in "preview" mode.

Do agree in having #18 done before doing so, `Scala.js` is creating a huge amount of momentum these days, and we really do wan't to ride that.

**Comment by julien-truffaut** [comment]
I can create an experimental module in Monocle for cats - state. I am not using state much so I would need some help.

**Comment by refried** [comment]
@non I think it’s a good plan, I use Monocle even to create lenses for use with scalaz. Lens lets you modify a component of your value.  State and Lens go hand in hand because as you are composing operations that affect your state, you want to throw in a few that were designed to affect just a component of your state. Basically the State version of lifting a function through a Lens.

I think Lenses in cats would basically mean syntax on State (there may be other uses I’m not familiar with).  I wish there was a way that we could have all the modularity (separate integration project) without additional import boilerplate though.  If we’re putting support behind Monocle (and I don’t know why we wouldn’t) I would just put theater methods on State directly.  There should also probably be additional syntax on Lens though, and @julien-truffaut has been working on that too.

Scalaz has a lot more combinators than Monocle, I haven't learned the reasons behind all of them yet.

**Comment by refried** [comment]
sorry a few bad autocompletes that i guess i cant fix from the mobile interface.

**Comment by ceedubs** [comment]
I think Cats could certainly be helpful without scala.js support, but this is clearly something that people are excited about, so I've added #18 to the 0.1.0 milestone. If everything else for the release is finished and we don't have scala.js support yet, we can reconsider whether or not it should be a blocker.

**Comment by InTheNow** [comment]
re scala.js support. One of the stumbling blocks for sjs support is that the CrossProjects did not work with scoverage, but a fix for that will be in next release of scalajs, about one week away :)

**Comment by ceedubs** [comment]
I've been thinking about this some more, and I'm feeling like we should get out a minimal viable product as 0.1.0. As far as I'm concerned, a stable release of non/algebra may be all that's needed for an MVP.

I'm all for better documentation, Spark support, and scala.js support. But at the point that a library is extremely well-documented and runs on multiple platforms, I feel like it's at a 1.0 status, not 0.1.

@non what do you think about me relabeling the current milestone to 1.0 and adding a 0.1 milestone with an issue for depending on an algebra release?

**Comment by rossabaker** [comment]
:+1:  v1.0 is a solemn step.  v0.x is a casual invitation to wider use, which helps drive a better v1.0.  Let's not overthink this.

**Comment by InTheNow** [comment]
re scalajs integratation, the only blocker is https://github.com/scalatest/scalatest/issues/631. Indeed, I could even publish an interim version and get everything ported in a few days....

Alternative suggestion: Just announce a release date (eg 1st August) and see what makes it...?

**Comment by julien-truffaut** [comment]
:+1:  I agree with @rossabaker

**Comment by InTheNow** [comment]
Another peanut from said gallery, why not just move issues/PR's that do not make 0.1.0 into the 0.2.0 milestone?

**Comment by non** [comment]
I agree with @ceedubs. I'll try to work to make this happen ASAP.

**Comment by InTheNow** [comment]
:+1:

**Comment by ceedubs** [comment]
For now I moved the existing 0.1.0 issues to a new (and arbitrary) [1.0 milestone](https://github.com/non/cats/milestones/cats-1.0.0). I'm not attached to this breakdown, so we can freely change this as time goes on. I just wanted to give these issues some sort of classifier since people thought they were important.

Now the only 0.1.0 issue is #396.

**Comment by mkotsbak** [comment]
#396 is now solved. So could it be released? Will it support sjs?

**Comment by non** [comment]
This is issue has been resolved by the release of Cats 0.1.2: https://github.com/non/cats/blob/master/CHANGES.md

Algebra does not currently support Scala.js either, so we are still working to get the full dependency chain upgraded. Right now the biggest problem is that sbt-release and sbt-scalajs seem to have [problems working together](https://github.com/InTheNow/sbt-scalajs/issues/19).

**Comment by InTheNow** [comment]
Also, discipline is not released, despite https://github.com/typelevel/discipline/pull/13
