### ISSUE TITLE
Link to "herding cats"

### ISSUE THREAD

**Issue by ceedubs** [non/cats#358]
@eed3si9n has an excellent [herding cats](http://eed3si9n.com/herding-cats/) resource. We should link to it in our documentation.

The biggest question is where this link belongs. It would probably be nice to have a learning resources section on the [documentation site](http://non.github.io/cats/).

**Comment by non** [comment]
Yes, I think a *resources for learners* section is a good idea.

**Comment by feynmanliang** [comment]
I'll take this issue
