### ISSUE TITLE
Broken link to typeclasses page from homepage

### ISSUE THREAD

**Issue by davidallsopp** [non/cats#365]
The "Modularity" section of the homepage (https://github.com/non/cats/blob/master/docs/src/site/index.md) links to _tut/typeclasses.html, which results in a 404 Not Found. I'm guessing this should just be a link to typeclasses.html but I am not familiar with the tut structure and templates - there's a docs/src/site/typeclasses.md that includes _tut/typeclasses.md...

**Comment by ceedubs** [comment]
Thank you for taking the time to create this issue, @davidallsopp!
