### ISSUE TITLE
Annotate the types of implicit instances

### ISSUE THREAD

**Issue by non** [non/cats#4]
As @retronym says:

> I'd suggest to annotate the types of implicits as a rule around the code base.
> It is too easy to have overly-specific structural types inferred for
> implicit val fooInstance = new A with B { .... }

**Comment by milessabin** [comment]
Yes, definitely.

**Comment by adelbertc** [comment]
Are there places where this isn't being done? grep-ed around the codebase and everything seems to be annotated. That, or I'm bad at grep, which is quite possible.

**Comment by non** [comment]
I think previously there were. They may all be fixed now.

**Comment by ceedubs** [comment]
I think they are all fixed except some places where we have simulacrum TODOs like [here](https://github.com/non/cats/blob/3502bd42ce75725f8068dd12cc90d2b0bf222fd8/core/src/main/scala/cats/syntax/apply.scala#L6).
