### ISSUE TITLE
Create Contributor's Guide

### ISSUE THREAD

**Issue by non** [non/cats#40]
I've mentioned this while talking to many people, so I think it's something that we should get started on sooner rather than later.

Here are some things I imagine it doing:

1. Set expectations for contributors
2. Explain basic workflow, discussions, PR process, etc.
3. Talk about project structure, modules, etc.
4. Explain fundamental guiding principles
5. Lay out *best practices* and encourage consistency
6. Clearly document any exceptions or gotchas

We could use a wiki but I think I'd prefer a single Markdown document. I will try to start on this ASAP.

**Comment by ceedubs** [comment]
I plan on putting together a draft (that I'm sure will be heavily revised based upon feedback) for this within the next 36 hours.

**Comment by non** [comment]
One suggestion here -- let's push the branch used for this to origin, so that it is easier for different folks to push small fixes directly. I feel like the PR-to-a-PR could get tedious here, and we'll all be able to sign-off before it actually gets merged.

**Comment by ceedubs** [comment]
@non sounds like a good plan.

**Comment by stew** [comment]
@ceedubs please take into consideration the discussion in this thread: #25 raised by @julien-truffaut

**Comment by ceedubs** [comment]
I created a rough draft (really more of a skeleton) on a [contributor-guide](https://github.com/non/cats/blob/contributor-guide/CONTRIBUTING.md) branch. It is still mostly TODOs, but I wanted to get the general approach out there to see what people thought of it. Let me know what you think and I can keep trucking after work today if I'm trucking in the right direction.

**Comment by ceedubs** [comment]
Draft PR submitted: #47

**Comment by ceedubs** [comment]
I'm closing this since #47 was merged. I think we should create specific issues for any items we want to be updated in the contributor guide.
