### ISSUE TITLE
Create release notes for 0.1.1

### ISSUE THREAD

**Issue by non** [non/cats#410]
We should have some kind of change log with release notes.

At a minimum we should credit everyone who helped on the release. Since there is no prior release we probably don't have to enumerate every change, but we should try to give an overview of what is available, what may be lacking, and any assurances (or lack of assurances) users of this release can have.

This is relatively high-priority (we probably should have done this before announcing the release).

**Comment by ceedubs** [comment]
I think we are far enough past 0.1.1 now that we can forget about this. We should be diligent about release notes going forward (and so far have been I think).
