### ISSUE TITLE
Explain how to build just for JVM/JS in README

### ISSUE THREAD

**Issue by non** [non/cats#429]
Once we've merged scala.js support, full builds will potentially take longer, especially for the very first build.

We should probably acknowledge this in the README (or somewhere) and explain how to build/test just for JVM or JS.

**Comment by non** [comment]
Relatedly, when the projects I build were first ported over to scala.js, I noticed that my SBT would frequently crash. I ended up changing my memory settings to be more generous (and a few other things) and then the builds completed. We should include these options too so that people who want to do a full build don't get discouraged.

**Comment by InTheNow** [comment]
Regarding the SBT setup, the easiest solution would be for users to @paulp 's [sbt  extra](https://github.com/paulp/sbt-extras) as this would read in the projects `.jvmopts` by default. Plus they would get the extra goodies, too

**Comment by InTheNow** [comment]
So, would adding https://github.com/paulp/sbt-extras/blob/master/sbt to the project root solve this issue? Other projects do this, eg https://github.com/scalaz/scalaz-stream

**Comment by paulp** [comment]
[The downside](https://twitter.com/extempore2/status/633395041545748480) is that it adds a new way to bit rot.

**Comment by InTheNow** [comment]
> It looks like in order to run the validate sbt command now I need to have node installed. Is that right?
> We should probably add that to our contributing documentation (which I think currently is split between the readme and CONTRIBUTING.md

+1
