### ISSUE TITLE
Spelling: type class vs. typeclass

### ISSUE THREAD

**Issue by fthomas** [non/cats#441]
I've noticed that we are inconsistent wrt to the spelling of "type class" and "typeclass". The README uses  mostly "type class" while docs/src/site/index.md uses "typeclass" exclusively. For the sake of robotic consistency, can we agree on one spelling?

**Comment by travisbrown** [comment]
:+1: for consistency, and :+1: for two words.

There's a discussion of this question at the end of [the second section of the Typeclassopedia](https://wiki.haskell.org/Typeclassopedia), which makes an argument from history for "type class".

**Comment by non** [comment]
I agree with "type class" and also with the push for consistency. Thanks for noticing this.

**Comment by adelbertc** [comment]
:+1: type class

**Comment by milessabin** [comment]
+1

**Comment by fthomas** [comment]
I'm also for "type class". As an additional data point, Wikipedia also uses two words: https://en.wikipedia.org/wiki/Type_class

I'll prepare a PR then later this week.

**Comment by fthomas** [comment]
Closed by #446
