### ISSUE TITLE
add cats.arrow.Choice

### ISSUE THREAD

**Issue by julien-truffaut** [non/cats#463]
see [scalaz.Choice](https://github.com/scalaz/scalaz/blob/series/7.2.x/core/src/main/scala/scalaz/Choice.scala)

required for https://github.com/julien-truffaut/Monocle/issues/235

**Comment by non** [comment]
Sounds good to me.

**Comment by stew** [comment]
:+1:

**Comment by adelbertc** [comment]
:+1:

**Comment by adelbertc** [comment]
i got this.

**Comment by julien-truffaut** [comment]
see https://github.com/non/cats/issues/463

**Comment by adelbertc** [comment]
Merged.
