### ISSUE TITLE
Foldable fold name clash with TraversableOnce fold

### ISSUE THREAD

**Issue by drostron** [non/cats#482]
It might be nice to have `Foldable`'s `fold` available in postfix style on `TraversableOnce` instances. @ceedubs suggested an alias in a [gitter discussion](https://gitter.im/non/cats?at=55dd09cf004c3e375ad0be7d).

e.g.
```scala
scala> def i[T : Monoid](v: List[T]) = Foldable[List].fold(v)
i: [T](v: List[T])(implicit evidence$1: cats.Monoid[T])T

scala> def j[T : Monoid](v: List[T]) = v.fold
<console>:16: error: missing arguments for method fold in trait TraversableOnce;
follow this method with `_' if you want to treat it as a partially applied function
       def j[T : Monoid](v: List[T]) = v.fold
                                         ^
```

**Comment by drostron** [comment]
Are there thoughts on potential aliases such as `suml`, `foldSum`, `foldl`, `foldL`, ...? Further is there interest in having a right associative monoidal fold?

**Comment by adelbertc** [comment]
I'd like `combineAll` since it's `Monoid#combine`, and there's already a `Monoid#combineAll` with the same signature
