### ISSUE TITLE
sbt-doctest for Scaladoc

### ISSUE THREAD

**Issue by adelbertc** [non/cats#487]
https://github.com/tkawachi/sbt-doctest

**Comment by fthomas** [comment]
:+1:

I've added it to scalaz-stream (https://github.com/scalaz/scalaz-stream/pull/248) a year ago and it hadn't caused any issues there. But I'm biased since I'm also a contributor of sbt-doctest. :-)

**Comment by non** [comment]
In the interest of type-checking our documentation I definitely support this. I guess I'd want to see it in action here to make sure it is reasonable. I worry that there would be a sea of imports required, but maybe not?

**Comment by travisbrown** [comment]
@non If demonstrating basic functionality of a method requires a sea of imports I think that's a problem in itself, and sbt-doctest is a good way to make _us_ feel that pain first. :smile:

**Comment by stew** [comment]
I'd love to see doctest

**Comment by ceedubs** [comment]
I just gave this a try and ran into https://github.com/tkawachi/sbt-doctest/issues/56. I tried to selectively disable the unused import flag in tests, but my SBT skills failed me. Does anyone with a better grasp on SBT want to give it a try?

**Comment by ceedubs** [comment]
Big thanks to @fthomas for the quick turnaround on a fix for https://github.com/tkawachi/sbt-doctest/issues/56. I'll start on this.

**Comment by fthomas** [comment]
fixed by #724
