### ISSUE TITLE
Traverse - FoldMap consistency

### ISSUE THREAD

**Issue by julien-truffaut** [non/cats#500]
`foldMap` and `traverse` are not always consistent, i.e.

```scala
  def foldMap[F[_], A, B: Monoid](fa: F[A])(f: A => B): B = 
    traverse(fa)(a => Const(f(a))).getConst
```

for example:

```scala
List(1,2,3).traverseU(i => Const(List(i))).getConst == List(3,2,1)
List(1,2,3).foldMap(List(_)) == List(1,2,3)
```

Shall we add a law to check this?

see: https://hackage.haskell.org/package/base-4.8.1.0/docs/src/Data.Traversable.html#foldMapDefault

**Comment by non** [comment]
:+1: 

In fact, we may want laws to check all our derived methods which can be overridden for performance reasons (i.e. we'd either want laws, or to make derived methods `final`).

**Comment by adelbertc** [comment]
Fixed
