### ISSUE TITLE
add typeclass instances for AnyVal

### ISSUE THREAD

**Issue by stew** [non/cats#53]
we should have Show instances in std for things like Float, Double, Int, Long, etc

**Comment by mandubian** [comment]
I started implement this one but I have a question:
Do we export all algebra instances too?

If yes, creating one trait per AnyVal subclass which extends the trait from algebra project and then mixing them all in a ig AnyValIntances trait doesn't please me so well. It will increase compile-time a lot... For example:

```
trait IntInstances extends algebra.std.IntInstances { ... }

trait AnyValInstances extends IntInstances with DoubleInstances... { ... }
```

**Comment by stew** [comment]
you want to be able to import, for example, Int instances but not all the other Anyval instances?

**Comment by mandubian** [comment]
So we would have separated traits inheriting algebra traits & objects for
int, double, short, etc... right?

**Comment by julien-truffaut** [comment]
I rarely saw the benefit of AnyVal import, most the time you either want a la carte import (e.g. import cats.std.int._) or all instances (import cats.std.all._)

**Comment by stew** [comment]
sounds perfectly reasonable to me.

**Comment by mandubian** [comment]
Exactly my feelings actually...
I'll create the PR and push it for comments ;)
Le 4 févr. 2015 09:32, "Julien Truffaut" <notifications@github.com> a écrit
:
