### ISSUE TITLE
Monad null instance

### ISSUE THREAD

**Issue by gabro** [non/cats#541]
```
import cats._
import cats.data._
import cats.std.future._
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Future

type Response[A] = OptionT[Future, A]

implicit val monadInstance: Monad[Response] = Monad[({ type x[A] = OptionT[Future, A] })#x]
// null
```

I would expect this not to compile, but it returns `null` instead.

Any ideas?

**Comment by gabro** [comment]
Ok, weird, dropping the `Monad[Reponse]` return type from `monadInstance` makes it work.

I would definitely expect a compile-time error here.

**Comment by ceedubs** [comment]
@gabro this boils down to essentially being the same as:

```scala
scala> implicit val s: String = implicitly[String]
s: String = null
```

It's unfortunate and I've accidentally done this sort of thing a number of times. One workaround is to do something like:
```scala
implicit val monadInstance: Monad[Response] = OptionT.optionTMonad
```

I would probably consider this as more of a scala compiler issue than something that could/should be addressed in Cats. If there's something that we could do in Cats to help, I'm open to the idea though.

**Comment by gabro** [comment]
Oh, I see, that makes sense (for as much as a compiler issue can make sense).
Thanks.

Closing this, since I agree this is not related to Cats, and I've no idea of how to tackle it, other than go and "fix" the compiler.
