### ISSUE TITLE
Proposed laws for Bifunctor

### ISSUE THREAD

**Issue by agenovese** [non/cats#557]
Currently there are no laws associated with Bifunctor, I'd like to propose the following:

Bifunctor Identity:

`fa.bimap(identity, identity) <-> fa`

Bifunctor Composition

`fa.bimap(f1, f2).bimap(g1, g2) <-> fa.bimap(f1 andThen g1, f2 andThen g2)`

**Comment by fthomas** [comment]
See also #509. It is also [good practice](https://github.com/non/cats/blob/master/CONTRIBUTING.md#let-us-know-you-are-working-on-it) to add a comment here if you're working on this.

**Comment by fthomas** [comment]
Fixed by #559
