### ISSUE TITLE
Order documentation on typeclasses based on recommended learning sequence?

### ISSUE THREAD

**Issue by danishin** [non/cats#565]
Great library and especially an amazing documentation!

I just went through all of [your documentation on typeclasses](http://non.github.io/cats//typeclasses.html).

And I was thinking maybe it's better to order the typeclasses according to the recommended learning sequence instead of alphabetically since a lot of concepts are built upon some previous concepts?

I found the following sequence works well for me (disregarding the ones not ready yet).

Functor -> Apply -> Applicative -> Monad -> Id -> 
Semigroup -> Monoid -> SemigroupK ->
Traverse -> Foldable

Logical progression would be starting with `Functor` to `Monad` and `Semigroup` to `Monoid` and finally typeclasses that mix in the previous fundamental typeclasses like `Traverse` and `Foldable` where `Foldable` is extension to `Traverse`.

**Comment by ceedubs** [comment]
@danishin thank you for taking the time to document helpful suggestions for this.

#403 already exists for this. Reducing the barrier to functional programming is a primary goal of Cats, so I think this is one of the most important tickets we have open right now. I'm going to go ahead and close this in favor of that one, but I'll be sure to link to your suggestions from there.
