### ISSUE TITLE
Should WriterT be in a separate module?

### ISSUE THREAD

**Issue by ceedubs** [non/cats#573]
Recently `WriterT` was added to the core module (in the data package). Should it go into a separate module?

Currently `StateT` lives in a separate `state` module. Mostly this is because `State` depends on `Free` for trampolining. However, as far as I know, having a separate `state` module hasn't led to any complaints. It makes me wonder if `WriterT` should also be in a separate module, as it's not essential to "core" Cats functionality. I suspect many people will use Cats without finding themselves reaching for `WriterT`.

**Comment by refried** [comment]
> having a separate state module hasn't led to any complaints.

Do we have a sense of how many people are using the state module?

**Comment by ceedubs** [comment]
@refried no, I have no idea. I suspect very few.

**Comment by dwijnand** [comment]
Now that #765 is merged, the state and free modules are now dead, which might be of interest for this issue.

**Comment by ceedubs** [comment]
@dwijnand good point. If `StateT` is in core, it probably makes sense for `WriterT` to be in there too. A PR would be welcome from anyone who is interested in doing this work.

**Comment by lukiano** [comment]
will there be a MonadTell / MonadListen for WriterT?

**Comment by ceedubs** [comment]
@lukiano there probably should be. Feel free to create a separate issue for that if it's something you would use.

**Comment by DavidGregory084** [comment]
@ceedubs I'm not sure what the objective of this issue is anymore now that there are no separate modules; especially with reference to #785. Should this be closed?

**Comment by ceedubs** [comment]
@DavidGregory084 ah thanks. I was confused when I wrote https://github.com/non/cats/issues/573#issuecomment-169318605 (see the edit I just added). I'll close this out.
