### ISSUE TITLE
Inference issues with Id

### ISSUE THREAD

**Issue by ceedubs** [non/cats#580]
I can fetch the `Applicative` instance for a `Kleisli` of a `List` no problem:

```scala
scala> import cats._, data._, implicits._
import cats._
import data._
import implicits._

scala> Applicative[Kleisli[List, Int, ?]]
res0: cats.Applicative[[γ]cats.data.Kleisli[[+A]List[A],Int,γ]] = cats.data.KleisliInstances$$anon$2@10c03632
```

However, if I use `Id` instead of `List`, I run into issues:

```scala
scala> Applicative[Kleisli[Id, Int, ?]]
<console>:20: error: could not find implicit value for parameter instance: cats.Applicative[[γ]cats.data.Kleisli[[A]A,Int,γ]]
       Applicative[Kleisli[Id, Int, ?]]
                  ^
```

This smells like a scala compiler bug, because it works if I call `kleisliApplicative` explicitly:

```scala
scala> val F: Applicative[Kleisli[Id, Int, ?]] = Kleisli.kleisliApplicative[Id, Int]
F: cats.Applicative[[γ]cats.data.Kleisli[[A]A,Int,γ]] = cats.data.KleisliInstances1$$anon$4@12dd5884
```

Questions:
* Why exactly does this happen?
* Does this have to do with the way we have Id defined? If so, can we change the way we define it to get around this?
* If we can't work around this with the way we have Id defined, should we work around it by providing explicit instances related to Id in a bunch of places?

**Comment by fthomas** [comment]
This reminds me of the problem I had in #267. I guess it is because `Id` and `NonEmptyList` are actually type aliases.

**Comment by milessabin** [comment]
Is there an explicit instance for `Id`? If there isn't, try adding one.

**Comment by ceedubs** [comment]
@milessabin an explicit `Kleisli` instance for `Id`? If that's what you mean, then no there isn't. I looked into it, and this is what scalaz does (and tbh is the only way `Reader` is usable). It does require a lot of implicit prioritization to avoid ambiguous implicits if users add their own type aliases around `Kleisli` though. See [this StackOverflow post](http://stackoverflow.com/questions/11913128/scalaz-7-why-using-type-alias-results-in-ambigous-typeclass-resolution-for-rea).

**Comment by milessabin** [comment]
Yes, that is what I meant.

Do you want to see if you could use export-hook to help deal with the implicit prioritization issues?

**Comment by ceedubs** [comment]
@milessabin that sounds like it could be really nice. I haven't tried out export-hook at all, and it may be a while before I get around to this, but it sounds like it's definitely worth a shot.

**Comment by ceedubs** [comment]
I'm working on this. For now I'm going to use the familiar prioritization via subtyping approach, but I think it'd be neat if export-hook took care of this in the future.
