### ISSUE TITLE
Add syntax for Validated

### ISSUE THREAD

**Issue by coltfred** [non/cats#585]
We should support 
```
.valid
.invalid
.invalidNel
```
as syntax to lift values into Validated objects.

This should be added by importing `cats.syntax.validated._`.

**Comment by coltfred** [comment]
I'll start on this and should have a PR ready shortly.

**Comment by ceedubs** [comment]
:+1:

It would probably be nice to have `toValid` and `toValidNel` (and maybe `toInvalid` and `toInvalidNel`?) added to `OptionOps` if you are feeling ambitious :)

**Comment by coltfred** [comment]
@ceedubs Correct. I'll do that.

**Comment by coltfred** [comment]
This has been addressed and merged. Closing.
