### ISSUE TITLE
Let's talk the next release (again)

### ISSUE THREAD

**Issue by travisbrown** [non/cats#594]
This is a follow-up to #486, and some of the conversation there (and [on Gitter this morning](https://gitter.im/non/cats?at=5637888a79a64a4a1853277d)) is relevant.

A lot has happened since 0.2.0, and there seems to be general agreement that we're ready for an 0.3.0 release. From my (totally selfish) perspective there's no real need for this to happen before Shapeless 2.3.0, which I'm waiting on for circe 0.2 anyway.

If there are particular issues that people would like to see resolved before 0.3.0, maybe it would be a good idea to attach a new milestone to them? Otherwise I'm happy to start putting together a draft of release notes for review.

**Comment by non** [comment]
I'm fine with doing this now. As far as I know, things are in a relatively coherent stage.

Some future release milestones I can think of are:

 - Removing default implementations from type classes (#168)
 - Integration with *catalysts* etc. (mostly an internal change)
 - Type tagging (related to #425)
 - Adding monoidal, reworking applicative, syntax, etc. (#555)
 - Some kind of async/task support (#32)
 - Better *simulacrum/machinist* integration (possibly through *typeclassic*)

I don't think 0.3.0 needs to wait for any of these, I just wanted to let you all know what was on my mind.

**Comment by ceedubs** [comment]
I have already said so on Gitter, but just for to make it official, :+1: for an immediate-ish 0.3.0 release.

**Comment by fthomas** [comment]
I'm a fan of "release early, release often", so :+1: from me.

**Comment by travisbrown** [comment]
I've gotten bogged down in circe stuff the past couple of days, and now that [0.2.0 is out](https://github.com/travisbrown/circe/releases/tag/v0.2.0) this is less urgent for me, but I haven't forgotten my promise to write up release notes. :smile:

**Comment by travisbrown** [comment]
This was fixed by bea10d975cb72bacdf066e5008a40a936cbd437c and can be closed now.
