### ISSUE TITLE
review bimonad laws

### ISSUE THREAD

**Issue by tpolecat** [non/cats#595]
Kind of random ... @jedws just referenced [this paper](http://arxiv.org/pdf/0710.1163v3.pdf) (pdf link) which describes an entwining property of bimonads that may or may not be captured in the current laws. It looks like it goes beyond the point/extract symmetry but I didn't try to make sense of it. Mostly I just like the word "entwining".

**Comment by non** [comment]
The important definition is 4.1 on page 12.

I think to paraphrase it into Scala we want to be sure that:

```scala
extract(flatmap(ffa)(identity)) <-> extract(map(ffa)(extract))
coflatmap(pure(a))(identity) <-> map(pure(a))(pure)
extract(pure(a)) <-> a
```

(These three laws correspond to the three diagrams.)

**Comment by non** [comment]
This paper actually leaves out one of our current laws, namely:

```scala
F.pure(F.extract(fa)) <-> fa
```

What do you all think? Intuitively I can see why it might be nice to assume this exists, but it's not mentioned in the paper.
