### ISSUE TITLE
add higher arity methods to apply

### ISSUE THREAD

**Issue by stew** [non/cats#61]
apply3, map3, apply4, map4... don't know if we should have some uniform arity where these things stop, in scalaz it is all over the place, some of these stop at 5 some at 8 some at 12, etc...

**Comment by mpilquist** [comment]
#64 adds `applyN` -- we still need `mapN` and `tupleN`. For example: https://github.com/mpilquist/Structures/blob/24d40bd39db7f1cf60bd63154b44540deb7f667e/core/src/main/scala/structures/Apply.scala

**Comment by wedens** [comment]
I'll add them

**Comment by ceedubs** [comment]
Fixed by #64
