### ISSUE TITLE
Kleisli: local and lmap are the same

### ISSUE THREAD

**Issue by ceedubs** [non/cats#624]
@philwills has pointed out [on gitter](https://gitter.im/non/cats?at=564314316420c33467a16021) that `local` and `lmap` on `Kleisli` are essentially the same thing.

```scala
def lmap[C](f: C => A): Kleisli[F, C, B] =
  Kleisli(run compose f)

def local[AA](f: AA => A): Kleisli[F, AA, B] =
  Kleisli(f.andThen(run))
```

We should probably either remove one of them or make one just an alias for the other (and document that it is so).

My personal preference would be to drop one of them. I think that aliases tend to just make it harder on the user, as it just gives them more to learn.

**Comment by adelbertc** [comment]
I personally prefer `local` since the only time I've used it is to "widen" some sort of local config/environment into a more global one, but if there is a more fundamental reason for it being called `lmap` that's fine by me too.

**Comment by ceedubs** [comment]
@adelbertc at the risk of telling you something that you already know, `lmap` comes from `Profunctor`. Having said that, the name of the `Kleisli` method doesn't necessarily need to match up with the name of the method in the type class instance. I would imagine we have other examples where there is a more meaningful name that we use for the method on the data structure.

**Comment by adelbertc** [comment]
Ah, I did not know that :-)

That being said I agree with having a more meaningful name.. in which case I may swing back to having an alias for one of them or just keeping `local` :P

**Comment by ceedubs** [comment]
Just keeping local sounds good to me.
