### ISSUE TITLE
Add OptionT.fromF

### ISSUE THREAD

**Issue by lambdista** [non/cats#659]
I noticed that the 0.3.0 version includes a useful `OptionT.fromOption` function. It lets you build an `OptionT` from an `Option`. 

Wouldn't it be the case to add an `OptionT.fromF` that lets you build an `OptionT` from an `Applicative F`? As in:

```scala
scala> OptionT.fromF(List(8))
res1: cats.data.OptionT[List,Int] = OptionT(List(Some(8)))
```

Of course I'd accept suggestions for a better name than `fromF`.

**Comment by ceedubs** [comment]
Thanks for the suggestion @lambdista. Just to make sure I understand clearly, you're talking about a function that will take an `F[A]` and lift it into an `OptionT[F, A]` where we essentially `map` on the `F[A]` and wrap every `A` in `Some`, right?

**Comment by lambdista** [comment]
Thanks for your answer @ceedubs. Yes, that's exactly what I mean. About your thoughts:

* You're totally right, I think we could get by with just a `Functor` too.
* Yes, it's essentially `liftM` from `MonadTrans` but, as you correctly wrote, having an `OptionT`-specific method would do no harm and require a less constrained `Functor` requirement compared to the `Monad` of `liftM`.

Let me know if you want me to add it and send a PR. Thank you.

**Comment by ceedubs** [comment]
I'd like this :+1:. Anyone else?

I'd propose `liftF` as a name to parallel `liftM` but with `Functor` instead of `Monad`.

**Comment by non** [comment]
:+1:

**Comment by lambdista** [comment]
That's great! `liftF` is perfect. :+1:

**Comment by lambdista** [comment]
Implemented, added test and updated related docs. Let me know if you want to me to change/add anything. Thank you.

**Comment by ceedubs** [comment]
Completed by #667.
