### ISSUE TITLE
SemigroupK and MonoidK instances for Function1

### ISSUE THREAD

**Issue by ceedubs** [non/cats#684]
#478 added `SemigroupK` and `MonoidK` instances for `Kleisli`. We should be able to provide similar instances for `Function1`.

I think we can also add a `Semigroup` instance for `Function1`, as it currently is missing this but has a `Monoid` instance (with a stricter constraint on `B`).

**Comment by lvicentesanchez** [comment]
I could do this; I have some free time this weekend.

**Comment by ceedubs** [comment]
Thanks @lvicentesanchez! I'v marked it as in progress.

**Comment by mikejcurry** [comment]
Should this close now? I don't have rights to do so.

**Comment by adelbertc** [comment]
Yep, thanks @mikejcurry
