### ISSUE TITLE
Free.foldMap throws a java.lang.ClassCastException

### ISSUE THREAD

**Issue by franciscodr** [non/cats#712]
As commented in a [Gitter conversation](https://gitter.im/non/cats?at=5660b8dd1da31ad605a8c321), when I try to transform a free monad to another monad like `Option`, `List` or `Future` using `foldMap`, I get a `java.lang.ClassCastException`.

I'm using cats 0.4.0-SNAPSHOT

**Comment by ceedubs** [comment]
Thanks for reporting, @franciscodr! I'll start to take a look at this.

**Comment by franciscodr** [comment]
@ceedubs After merging https://github.com/non/cats/pull/713, the example code works fine again. Thanks!
