### ISSUE TITLE
Move cats-free and cats-state in to cats-core?

### ISSUE THREAD

**Issue by mpilquist** [non/cats#760]
I don't recall the rationale for making the `cats.free` package its own module, but the way in which it forces `State` to be in its own module is a big enough of a disadvantage that I think we should reconsider.

This would also allow us to close https://github.com/non/cats/issues/573.

**Comment by travisbrown** [comment]
:+1:. I think modularity is a good goal, but I don't think this is a useful way to cut things. Together these two jars are less than 5% of the size of cats core, and I don't think separating them makes the API more intelligible in any way.

**Comment by stew** [comment]
:+1:

**Comment by refried** [comment]
Hooray!

**Comment by milessabin** [comment]
:+1:

**Comment by dwijnand** [comment]
Can be closed now that #765 is merged.
