### ISSUE TITLE
`combine` syntax appears to be behaving unexpectedly when kitchen sink importing

### ISSUE THREAD

**Issue by longcao** [non/cats#763]
`combine` and `|+|` are listed as aliases for one another but when using the kitchen sink imports, they appear to be routing to an unexpected implementation:

```scala
import cats.std.all._
import cats.syntax.all._

scala> Option("asdf") combine Option("qwer") 
res0: Option[String] = Some(asdf)

scala> Option("asdf") |+| Option("qwer") 
res1: Option[String] = Some(asdfqwer)

scala> scala.reflect.runtime.universe.reify { Option("asdf") |+| Option("qwer") }
res2: reflect.runtime.universe.Expr[Option[String]] = Expr[scala.Option[java.lang.String]](`package`.all.semigroupSyntax(Option.apply("asdf"))(`package`.all.optionMonoid(`package`.all.stringMonoid)).$bar$plus$bar(Option.apply("qwer")))

scala> scala.reflect.runtime.universe.reify { Option("asdf") combine Option("qwer") }
res3: reflect.runtime.universe.Expr[Option[String]] = Expr[scala.Option[java.lang.String]](`package`.all.toSemigroupKOps(Option.apply("asdf"))(`package`.all.optionInstance).combine(Option.apply("qwer")))
```

For now, I've decided to work around this by importing a bit more strictly down to what I want:

```scala
import cats.std.all._
import cats.syntax.semigroup._

scala> Option("asdf") combine Option("qwer")
res0: Option[String] = Some(asdfqwer)
```

**Comment by ceedubs** [comment]
[here](https://gitter.im/non/cats?at=5673212469a89a8f552f0c74) is a relevant gitter conversation

**Comment by ceedubs** [comment]
My initial reaction to this is that we should probably rename the `combine` on `SemigroupK` to `combineK` or something to avoid ambiguity. Separately, I think that I think that the `Semigroup[Option[A]]` instance should be the one derived from `SemigroupK[Option]` as opposed to the one derived from `Semigroup[A]`. This has been discussed before, but I can't recall what everyone thought. FWIW I believe this is what Idris does.

**Comment by milessabin** [comment]
This is going to be an issue for `Monoid` and `MonoidK` as well, right?

**Comment by milessabin** [comment]
And probably `Alternative`. See also #757.

**Comment by ceedubs** [comment]
I started putting together a PR for this, but I think that any change for this is going to run into conflicts with #757, so maybe we should hold on this until that one is merged.

**Comment by milessabin** [comment]
Or incorporate your changes into that?
