### ISSUE TITLE
Put laws next to type class definitions?

### ISSUE THREAD

**Issue by fthomas** [non/cats#81]
I'd like to discuss if the laws that govern the functions of type classes should be put next to their definitions. Here is an example of what I have in mind:
```scala
// this is Functor.scala

trait Functor[F[_]]  {
  def map = ...
}

trait FunctorLaws[F[_]: Functor] {
  def identity(...): Boolean = ...
  def associative(...): Boolean = ...
}
```
I see the following advantages:
 * it emphasizes the importance of laws
 * the type checked laws are in the vicinity of the type class definitions and not "hidden" between test code in the `laws` subproject
 * the laws can be used in the `laws` subproject
 * the laws are decoupled from test code

What do you think?

**Comment by non** [comment]
I'm sympathetic to this. Would you mind pasting a simple example here (i.e. `functor.Invariant[_]`) just so we could see what it would look like?

**Comment by fthomas** [comment]
@non here is one way to do it: https://github.com/fthomas/cats/compare/wip/move-laws

**Comment by julien-truffaut** [comment]
maybe it would read better if we would use syntax for laws?

**Comment by fthomas** [comment]
Updated the branch to use syntax for `Eq`. It looks a little bit better now.

**Comment by non** [comment]
So here's one concern -- if the laws fail you probably get little or not useful output.

In algebra, we use the `?==` to get output when `===` tests fail. Here's the relevant code:

https://github.com/non/algebra/blob/master/laws/src/main/scala/algebra/laws/package.scala#L23

Obviously we don't want `core` to depend on ScalaCheck. Is there some way we can put the laws in core while supporting using the ScalaCheck labels to get useful output?

**Comment by fthomas** [comment]
I wouldn't call it a solution, but we could let the laws return two things that should be equal instead of a `Boolean`:
```scala
  def invariantIdentity[A](fa: F[A]): (F[A], F[A]) =
    (F.imap(fa)(identity[A])(identity[A]), fa)
```
ScalaCheck could then take care of comparing those two values.

**Comment by non** [comment]
Right, or even just return the `(A, A, (A, A) => Boolean)` that algebra would be passing to `Ops.run` if you see what I mean.

**Comment by non** [comment]
You could argue this makes all the laws less readable. I'm willing to create some kind of DSL here, ideally we can have laws that are clearly specified in a useful place, but which also produce useful messages when they fail.

**Comment by fthomas** [comment]
I think a small DSL could make the laws as readable as the `Boolean`-returning versions. Just with something like `type Identity[A] = (A, A)` and `->` it reads a lot better. 

```scala
  def invariantIdentity[A](fa: F[A]): Identity[F[A]] =
    F.imap(fa)(identity[A])(identity[A]) -> fa
```

**Comment by ceedubs** [comment]
If `Identity[A]` is defined as anything other than `Identity[A] = A` I think it's going to really confuse people. Other than that a mini DSL sounds fine to me :)

**Comment by non** [comment]
I think the benefit of a DSL would be to enable other kinds of laws besides those based on identical pairs, so I think we'd want something slightly different here.

**Comment by fthomas** [comment]
I've now moved all current laws next to the type classes in my WIP branch (https://github.com/fthomas/cats/compare/wip/move-laws). The laws are now inner `trait`s of the type classes which avoids the evidence parameters and the `F.` prefixes. What do you think?

**Comment by fthomas** [comment]
I should add that the definitions of the laws in my WIP branch are similiar to how they are defined in scalaz.

**Comment by julien-truffaut** [comment]
@fthomas not sure to understand what's the benefit of having the law as inner trait?

**Comment by mpilquist** [comment]
While I agree that defining the laws in the same source file as the type class has a lot of benefits, it still feels like it's test code that's included in non-test artifacts.

Also, with unidoc, each type class can link directly to a laws trait defined in the laws JAR, providing similar benefits to the suggested solution, without bloating the core JAR.

Ultimately, I wonder if we can separate the laws from their binding to Discipline like in the suggestion above, but still include them in the laws JAR.

**Comment by fthomas** [comment]
@julien-truffaut as top-level class:
```
trait Invariant[F[_]] {
  def imap[A, B](fa: F[A])(f: A => B)(fi: B => A): F[B]
}

class InvariantLaws[F[_]](implicit F: Invariant[F]) {
  def invariantIdentity[A](fa: F[A]): (F[A], F[A]) =
    F.imap(fa)(identity[A])(identity[A]) -> fa
}
```
as inner trait:
```
trait Invariant[F[_]] {
  def imap[A, B](fa: F[A])(f: A => B)(fi: B => A): F[B]

  trait InvariantLaws {
    def invariantIdentity[A](fa: F[A]): (F[A], F[A]) =
      imap(fa)(identity[A])(identity[A]) -> fa
  }
}
```
The inner trait does not require the context bound `implicit F: Invariant[F]` and instead of `F.imap` you can just write `imap`.

**Comment by fthomas** [comment]
@mpilquist In retrospect my main concern was the tight coupling between the laws and discipline code. If there are proper ScalaDoc links from the type classes to the law traits, I think that is also ok for me.

**Comment by julien-truffaut** [comment]
I would also prefer the laws to be defined outside the TC trait. I agree with @fthomas a scaladoc link to reference the laws is a good documentation.

**Comment by fthomas** [comment]
Here is another proposal: https://github.com/fthomas/cats/compare/wip/move-laws2
 * each typeclass has now its dedicated `Laws` class in the `cats.laws` package
 * the `discipline` test code is moved into the `cats.laws.discipline` package

What do you think? Is this good enough to open a PR with these changes?

**Comment by mpilquist** [comment]
Looks good to me
