### ISSUE TITLE
scalaz-adapter subproject with cats instances for scalaz instances

### ISSUE THREAD

**Issue by refried** [non/cats#83]
I'll eventually take a crack at this if nobody beats me to it.  Unless there's a technical or philosophical reason not to?

**Comment by mpilquist** [comment]
From a technical perspective, I don't think we should have to rebuild the cats core project for each scalaz-core release. Hence, these types of binding projects need to be in independent repositories.

**Comment by travisbrown** [comment]
@rossabaker [started one](https://github.com/rossabaker/scataz) yesterday. My feeling is that this should probably live in a separate repo.

**Comment by non** [comment]
I agree about a separate repo.

**Comment by refried** [comment]
Good point.

**Comment by ceedubs** [comment]
It sounds like everyone agrees that this should be a separate repo. Since @rossabaker has created [scataz](https://github.com/rossabaker/scataz) I'm going to go ahead and close this issue.
