### ISSUE TITLE
Stack safety of lazy version of `foldRight` for `List`

### ISSUE THREAD

**Issue by ceedubs** [non/cats#88]
Cats defines a lazy version of `foldRight` on `Foldable`:
```scala
def foldRight[A, B](fa: List[A], b: Lazy[B])(f: (A, Lazy[B]) => B): Lazy[B] = {
```

Currently the [`List` implementation](https://github.com/non/cats/blob/0e4e235758645c432c5652f2653d0723c21e0773/std/src/main/scala/cats/std/list.scala#L43) is properly lazy, but it is not stack safe.

For example, consider the following derived `Foldable` method:
```scala
def exists[A](fa: F[A])(f: A => Boolean): Boolean =
  foldRight(fa, Lazy.eager(false))((a, b) => f(a) || b.force).force
```

This implementation will properly short-circuit for a small list:
```scala
scala> Foldable[List].exists(List(1, 2, 3)){x => println(x); x > 1}
1
2
res0: Boolean = true
```

However, for a large list it will throw a `StackOverflowError`. If a `List` is long enough that evaluating the predicate for each element is bad (and thus the `Lazy` variant is preferred), then it is likely large enough to throw this error. Therefore something needs to give.

Solutions that come to mind:
1. Use a version of `foldRight` for `List` that uses a combination of `reverse` and `foldLeft`. This would sacrifice laziness.
2. Use trampolining in the `List` implementation of the `Lazy` variant of `foldRight`. The trampolining would add significant overhead, but laziness would be preserved.

The second version seems preferable to me. If somebody is choosing to explicitly call the lazy (as opposed to strict) version, then they should get laziness.

However, I can also see the possibility of the abstraction becoming somewhat leaky. That is, someone defining `def foo[F[_]: Foldable]...` may start to think about which kinds of `F` people are going to be passing into this method so they can decide whether they want potential overhead of laziness or not. Having said that, it seems to me that the abstraction is still pretty leaky (or flat out wrong) if the types are suggesting they will get lazy evaluation but they don't.

What do people think? Beyond just choosing option 1 or option 2, are there other possibilities that come to mind?

**Comment by non** [comment]
My default stance would be for (2): we provide a maximally efficient strict version, and a maximally flexible lazy version.

The awkward thing is that it implies we have some kind of trampolining facility (or similar) available in `core`. I'm not sure this is a problem per se but so far we had talked about that machinery living somewhere else.

**Comment by ceedubs** [comment]
@non would we need it in `core` or just in `std`?

**Comment by non** [comment]
Oh, that's a good point. Maybe just having it in `std` would be enough, although it would mean that folks implementing `Foldable` would have to pull in `std`. But maybe that is OK.

**Comment by ceedubs** [comment]
Perhaps `free` could be its own module that `std` depends on?

**Comment by non** [comment]
It's also worth mentioning that we could create a specialized set of trampolines that might be more efficient in this case. I'm not saying we should do it, but it's definitely an option.

**Comment by non** [comment]
So interestingly I don't think we want free exactly.

Here's something I cooked up that does work pretty well:

```scala
  def foldr[A, B](ns: List[A], b: B)(f: A => Either[B => B, B]): B = {
 
    def eval(b: B, fs: List[B => B]): B =
      fs.foldLeft(b)((b, f) => f(b))
 
    @tailrec def loop(ns: List[A], fs: List[B => B]): B = {
      ns match {
        case Nil => eval(b, fs)
        case a :: rest => f(a) match {
          case Right(b) => eval(b, fs)
          case Left(g) => loop(rest, g :: fs)
        }
      }
    }
 
    loop(ns, Nil)
  }
```

**Comment by non** [comment]
There's also an option to use a special-purpose type instead of `Either` here. That could look something like:

```scala
sealed abstract class Fold[B]
case class End[B](b: B) extends Fold[B]
case class Run[B](f: B => B) extends Fold[B]

object Run {
  def id[B]: Run[B] = Run(identity)
}
```

...or similar.

**Comment by ceedubs** [comment]
@non that looks pretty similar to [something](https://github.com/scalaz/scalaz/pull/796#issuecomment-53159305) I pondered about for scalaz a little while ago. Except I was focusing on `foldLeft` while yours works for `foldRight`.

I like your approach. I could be talked into either the `Either`/`Or` approach or the custom `Fold` approach. Initially I'm a little partial to the `Either`/`Or` approach because it doesn't introduce a new concept. I'm open to the special-purpose type, but I wonder if there's a better name for it.

**Comment by non** [comment]
I'm working on this.
