### ISSUE TITLE
List-like structure with efficient appends

### ISSUE THREAD

**Issue by ceedubs** [non/cats#93]
I think it would be handy to have a list-like structure that supports efficient appends. This is handy for many use-cases, such as using a writer monad for logging.

The most obvious candidate is a [difference list](https://wiki.haskell.org/Difference_list).

Do others agree that something like this should be in the `data` module? Are there any alternatives to difference lists that should be considered?

**Comment by non** [comment]
Do you find that difference lists work better than double-ended queues? I would have guessed the latter would be a bit better in many cases. I guess difference lists work better for concatenation (as opposed to append/prepend) but with the overhead of trampolining?

**Comment by ceedubs** [comment]
@non you are right that the majority of the time I just need an efficient append, not concatenation. Admittedly I wasn't thinking about the difference between the two when I created this issue.

I think I've kind of blindly used `DList` for this sort of thing because a double-ended queues were only very recently added to scalaz. A double-ended queue would probably be better. I knew that I would regret saying "The most obvious candidate is a difference list"!

P.S. I love this sort of discussion. Thanks for helping me reconsider my assumptions!

**Comment by tpolecat** [comment]
For `Writer` you do need something with fast concat though, so it still makes sense to me to have `DList`.  What am I missing?

**Comment by ceedubs** [comment]
@tpolecat that's true. Writer was the example I gave, but in reality that's not what I'm doing usually when I use `DList`. I guess maybe what we are arriving at is that both would probably be helpful?

**Comment by stew** [comment]
so "do we implement general purpose datastructures" is like a can of worms. Do we just do this one? do we need a Dequeue? how about a Maybe? IList? ... slippery slope

My vote is that we label this stuff out of scope and put these data structures into a different project

**Comment by julien-truffaut** [comment]
I agree with @stew we can implement these sort of generic purpose data structures in another repo

**Comment by ceedubs** [comment]
Sounds reasonable.

**Comment by FranklinChen** [comment]
I currently use `DList` in a scalaz-based project, where I incrementally build up a sequence bottom up from a tree recursively using appends. Has someone provided a Cats-based repo yet with `DList` or should I roll my own since I do want to get off scalaz?

**Comment by ceedubs** [comment]
@FranklinChen [dogs](https://github.com/stew/dogs) would probably be a good place for this. It currently has a double-ended queue, which should be efficient for appends but perhaps not as efficient as `DList` for concatenating long lists (though `DList` does have quite a bit of overhead from thunks I believe). I imagine that @stew would be open to the idea of a `DList`.
